'use strict';
const express=require('express');const crypto=require('crypto');const settings=require('../settings');const {query}=require('../lib/db');const users=require('../services/userService');const keys=require('../services/apiKeyService');const tiers=require('../services/tierService');const usage=require('../services/usageService');const audit=require('../services/auditService');const pakasir=require('../services/pakasirService');const notifier=require('../services/ownerNotificationService');const orderService=require('../services/orderService');
const router=express.Router();
const fail=(res,status,error,message)=>res.status(status).json({success:false,error,message});
function sameOrigin(req,res,next){const origin=req.get('origin');if(origin){const host=`${req.protocol}://${req.get('host')}`;if(origin!==host)return fail(res,403,'CSRF_BLOCKED','Permintaan lintas-origin ditolak.');}next();}
function auth(req,res,next){const s=req.app.locals.getSession(req);if(!s)return fail(res,401,'UNAUTHENTICATED','Silakan login.');users.getUserForSession(s).then(u=>{if(!u)return fail(res,401,'UNAUTHENTICATED','Akun tidak ditemukan.');if(u.status!=='active')return fail(res,403,'ACCOUNT_RESTRICTED','Akun tidak aktif.');req.account=u;next();}).catch(()=>fail(res,503,'DATABASE_UNAVAILABLE','Layanan akun sementara tidak tersedia.'));}
function owner(req,res,next){if(!req.account?.isOwner)return fail(res,403,'OWNER_REQUIRED','Akses owner diperlukan.');next();}
function ip(req){return (req.ip||'').replace(/^::ffff:/,'').slice(0,45)||null;}
router.get('/api/keys',auth,async(req,res)=>{try{res.json({success:true,keys:await keys.listKeys(req.account.id),limit:tiers.getTier(req.account.tier).keys});}catch{fail(res,503,'DATABASE_ERROR','Data API key tidak tersedia.');}});
router.post('/api/keys',sameOrigin,auth,async(req,res)=>{try{const made=await keys.createKey(req.account,req.body?.name,String(req.get('Idempotency-Key')||'').slice(0,100)||null);await audit.writeAudit({actorUserId:req.account.id,action:'api_key_create',targetType:'api_key',targetId:made.record.id,ipAddress:ip(req)});res.status(201).json({success:true,key:made.key,record:made.record,warning:'Salin key sekarang. Plaintext hanya ditampilkan satu kali.'});}catch(e){fail(res,e.code==='KEY_LIMIT'||e.code==='KEYS_NOT_INCLUDED'?403:500,e.code||'KEY_CREATE_FAILED',e.message||'API key gagal dibuat.');}});
router.delete('/api/keys/:id',sameOrigin,auth,async(req,res)=>{try{const ok=await keys.revokeKey(req.account.id,req.params.id);if(!ok)return fail(res,404,'KEY_NOT_FOUND','API key tidak ditemukan atau sudah dicabut.');await audit.writeAudit({actorUserId:req.account.id,action:'api_key_revoke',targetType:'api_key',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true});}catch{fail(res,503,'DATABASE_ERROR','API key tidak dapat dicabut.');}});
router.post('/api/keys/:id/revoke',sameOrigin,auth,async(req,res)=>{try{const ok=await keys.revokeKey(req.account.id,req.params.id);if(!ok)return fail(res,404,'KEY_NOT_FOUND','API key tidak ditemukan atau sudah dicabut.');await audit.writeAudit({actorUserId:req.account.id,action:'api_key_revoke',targetType:'api_key',targetId:req.params.id,ipAddress:ip(req)});return res.json({success:true});}catch{return fail(res,503,'DATABASE_ERROR','API key tidak dapat dicabut.');}});
router.get('/pricing',(req,res)=>res.sendFile(require('path').join(__dirname,'..','views','pricing.html')));
router.get('/keys',auth,(req,res)=>res.sendFile(require('path').join(__dirname,'..','views','keys.html')));
router.get('/billing',auth,(req,res)=>res.sendFile(require('path').join(__dirname,'..','views','billing.html')));
router.get('/usage',auth,async(req,res)=>{try{const n=await usage.usageToday(req.account.id);const t=tiers.getTier(req.account.tier);res.json({success:true,tier:req.account.tier,used:n,limit:Number.isFinite(t.limit)?t.limit:null,remaining:Number.isFinite(t.limit)?Math.max(0,t.limit-n):null,resetAt:usage.nextUtcMidnight()});}catch{fail(res,503,'USAGE_UNAVAILABLE','Usage tidak tersedia.');}});
router.get('/api/dashboard',auth,async(req,res)=>{try{const [used,ks]=await Promise.all([usage.usageToday(req.account.id),keys.listKeys(req.account.id)]);const t=tiers.getTier(req.account.tier);res.json({success:true,user:{id:req.account.id,name:req.account.name,email:req.account.email,picture:req.account.picture,tier:req.account.tier},usage:{used,limit:Number.isFinite(t.limit)?t.limit:null,remaining:Number.isFinite(t.limit)?Math.max(0,t.limit-used):null},apiKeys:{used:ks.filter(k=>k.status==='active').length,limit:Number.isFinite(t.keys)?t.keys:null}});}catch{fail(res,503,'DATABASE_ERROR','Dashboard tidak tersedia.');}});
router.post('/api/orders',sameOrigin,auth,async(req,res)=>{try{const tier=String(req.body?.tier||'').toUpperCase();if(!tiers.purchasable.includes(tier))return fail(res,400,'INVALID_TIER','Paket pembelian tidak valid.');const amount=tiers.TIERS[tier].price;const code=`YAN-${tier}-${crypto.randomBytes(8).toString('hex').toUpperCase()}`;const idem=String(req.get('Idempotency-Key')||'').slice(0,100)||null;const rows=await query("INSERT INTO orders(user_id,order_code,tier,amount,status,expires_at,idempotency_key) VALUES($1,$2,$3,$4,'pending',now()+interval '2 hours',$5) ON CONFLICT(user_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET updated_at=orders.updated_at WHERE orders.tier=EXCLUDED.tier RETURNING id,order_code,tier,amount,status,created_at,expires_at",[req.account.id,code,tier,amount,idem]);if(!rows.length)return fail(res,409,'IDEMPOTENCY_CONFLICT','Idempotency key sudah dipakai untuk paket yang berbeda.');await audit.writeAudit({actorUserId:req.account.id,action:'order_create',targetType:'order',targetId:rows[0].id,metadata:{tier,amount},ipAddress:ip(req)});res.status(201).json({success:true,order:rows[0]});}catch{fail(res,503,'ORDER_FAILED','Order tidak dapat dibuat.');}});
router.post('/api/orders/:id/pakasir',sameOrigin,auth,async(req,res)=>{try{await orderService.expirePendingOrders();const method=String(req.body?.method||'qris');const rows=await query("SELECT * FROM orders WHERE id=$1 AND user_id=$2 AND status='pending' AND expires_at>now()",[req.params.id,req.account.id]);if(!rows.length)return fail(res,404,'ORDER_NOT_FOUND','Order tidak ditemukan atau kedaluwarsa.');const o=rows[0];const data=await pakasir.createTransaction(o.order_code,method,o.amount);const tx=data?.transaction||data?.data||data;const ref=String(tx?.txn_id||tx?.payment_number||tx?.transaction_id||tx?.reference||o.order_code);const p=await query("INSERT INTO payments(order_id,user_id,provider,payment_method,transaction_id,provider_reference,amount,status) VALUES($1,$2,'pakasir',$3,$4,$5,$6,'pending') ON CONFLICT(provider,transaction_id) WHERE transaction_id IS NOT NULL DO UPDATE SET updated_at=payments.updated_at RETURNING id,status,provider_reference,amount",[o.id,req.account.id,method,String(tx?.txn_id||tx?.transaction_id||o.order_code),ref,o.amount]);res.status(201).json({success:true,payment:p[0],gateway:{txn_id:tx?.txn_id||null,payment_link:tx?.payment_link||null,qr_string:tx?.qr_string||null,va_number:tx?.va_number||null,expired_at:tx?.expired_at||null,total_payment:tx?.total_payment||o.amount}});}catch(e){fail(res,502,e.code||'PAYMENT_PROVIDER_ERROR','Gateway pembayaran belum dapat memproses transaksi.');}});
router.post('/api/orders/:id/manual',sameOrigin,auth,async(req,res)=>{try{await orderService.expirePendingOrders();const method=String(req.body?.method||'manual_qris').toUpperCase();if(!['DANA','GOPAY','QRIS','BANK_TRANSFER'].includes(method))return fail(res,400,'INVALID_PAYMENT_METHOD','Metode manual tidak valid.');const proof=String(req.body?.proof_url||'').trim();if(!proof||!/^https:\/\//i.test(proof)||proof.length>2048)return fail(res,400,'INVALID_PROOF_URL','Bukti pembayaran harus berupa URL HTTPS yang valid.');const o=(await query("SELECT * FROM orders WHERE id=$1 AND user_id=$2 AND status='pending' AND expires_at>now()",[req.params.id,req.account.id]))[0];if(!o)return fail(res,404,'ORDER_NOT_FOUND','Order tidak ditemukan.');const existing=(await query("SELECT id,status FROM payments WHERE order_id=$1 AND provider='manual' AND status='pending' LIMIT 1",[o.id]))[0];if(existing)return fail(res,409,'PAYMENT_ALREADY_SUBMITTED','Bukti pembayaran untuk order ini sudah dikirim dan sedang menunggu approval owner.');const p=(await query("INSERT INTO payments(order_id,user_id,provider,payment_method,amount,proof_url,status) VALUES($1,$2,'manual',$3,$4,$5,'pending') RETURNING id,status,proof_url,created_at",[o.id,req.account.id,method,o.amount,proof]))[0];await audit.writeAudit({actorUserId:req.account.id,action:'manual_payment_create',targetType:'payment',targetId:p.id,metadata:{method,amount:o.amount,proofUrl:proof},ipAddress:ip(req)});const notice=await notifier.notifyManualPayment({order:o.order_code,user:req.account.name,email:req.account.email,tier:o.tier,amount:o.amount,method,proof});res.status(201).json({success:true,payment:p,instructions:process.env.MANUAL_PAYMENT_INSTRUCTIONS||'Bukti diterima. Status menunggu approval owner.',contact:settings.whatsappLink,notification:notice.sent?'sent':'provider_not_configured'});}catch(e){console.error('Manual payment failed:',e.code||'PAYMENT_CREATE_FAILED');fail(res,503,'PAYMENT_CREATE_FAILED','Pembayaran manual tidak dapat dibuat.');}});
router.get('/api/orders',auth,async(req,res)=>{try{await orderService.expirePendingOrders();res.json({success:true,orders:await query('SELECT o.*,p.id AS payment_id,p.payment_method,p.status AS payment_status,p.proof_url FROM orders o LEFT JOIN payments p ON p.order_id=o.id WHERE o.user_id=$1 ORDER BY o.created_at DESC',[req.account.id])});}catch{fail(res,503,'DATABASE_ERROR','Order tidak tersedia.');}});
router.get('/owner/api/endpoints',auth,owner,async(req,res)=>{res.json({success:true,endpoints:await query('SELECT * FROM endpoints ORDER BY name')});});
router.post('/owner/api/endpoints',sameOrigin,auth,owner,async(req,res)=>{try{const b=req.body||{};if(!b.name||!b.path||!/^\/[a-zA-Z0-9/_-]+$/.test(b.path)||!['GET','POST','PUT','PATCH','DELETE'].includes(String(b.method||'GET').toUpperCase()))return fail(res,400,'INVALID_ENDPOINT','Data endpoint tidak valid.');const r=await query('INSERT INTO endpoints(name,path,description,method,minimum_tier,locked,status,plugin) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[String(b.name).slice(0,100),b.path,String(b.description||''),String(b.method||'GET').toUpperCase(),tiers.TIERS[b.minimum_tier]?b.minimum_tier:'FREE',!!b.locked,b.status==='disabled'?'disabled':'active',b.plugin||null]);await audit.writeAudit({actorUserId:req.account.id,action:'endpoint_create',targetType:'endpoint',targetId:r[0].id,ipAddress:ip(req)});res.status(201).json({success:true,endpoint:r[0]});}catch{fail(res,409,'ENDPOINT_CREATE_FAILED','Endpoint gagal dibuat; path mungkin sudah terdaftar.');}});
router.patch('/owner/api/endpoints/:id',sameOrigin,auth,owner,async(req,res)=>{try{const b=req.body||{};const r=await query('UPDATE endpoints SET name=COALESCE($2,name),description=COALESCE($3,description),minimum_tier=COALESCE($4,minimum_tier),locked=COALESCE($5,locked),status=COALESCE($6,status),updated_at=now() WHERE id=$1 RETURNING *',[req.params.id,b.name??null,b.description??null,b.minimum_tier&&tiers.TIERS[b.minimum_tier]?b.minimum_tier:null,typeof b.locked==='boolean'?b.locked:null,['active','disabled'].includes(b.status)?b.status:null]);if(!r.length)return fail(res,404,'NOT_FOUND','Endpoint tidak ditemukan.');await audit.writeAudit({actorUserId:req.account.id,action:'endpoint_update',targetType:'endpoint',targetId:req.params.id,metadata:b,ipAddress:ip(req)});res.json({success:true,endpoint:r[0]});}catch{fail(res,500,'UPDATE_FAILED','Endpoint gagal diperbarui.');}});
async function setEndpointLock(req,res,locked){const r=await query('UPDATE endpoints SET locked=$2,updated_at=now() WHERE id=$1 RETURNING id,locked',[req.params.id,locked]);if(!r.length)return fail(res,404,'NOT_FOUND','Endpoint tidak ditemukan.');await audit.writeAudit({actorUserId:req.account.id,action:locked?'endpoint_lock':'endpoint_unlock',targetType:'endpoint',targetId:req.params.id,ipAddress:ip(req)});return res.json({success:true,endpoint:r[0]});}
router.post('/owner/api/endpoints/:id/lock',sameOrigin,auth,owner,(req,res)=>setEndpointLock(req,res,true));
router.post('/owner/api/endpoints/:id/unlock',sameOrigin,auth,owner,(req,res)=>setEndpointLock(req,res,false));
router.delete('/owner/api/endpoints/:id',sameOrigin,auth,owner,async(req,res)=>{await query('DELETE FROM endpoints WHERE id=$1',[req.params.id]);await audit.writeAudit({actorUserId:req.account.id,action:'endpoint_delete',targetType:'endpoint',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true});});
router.get('/owner/users',auth,owner,async(req,res)=>{const q=String(req.query.q||'').slice(0,100);res.json({success:true,users:await query('SELECT id,email,name,tier,status,created_at,banned_at,ban_reason FROM users WHERE email ILIKE $1 OR name ILIKE $1 ORDER BY created_at DESC LIMIT 100',[`%${q}%`])});});
router.get('/owner/users/:id',auth,owner,async(req,res)=>{const u=await query('SELECT id,email,name,picture,tier,status,daily_usage,last_usage_reset,created_at,banned_at,ban_reason FROM users WHERE id=$1',[req.params.id]);if(!u.length)return fail(res,404,'NOT_FOUND','User tidak ditemukan.');res.json({success:true,user:u[0]});});
router.post('/owner/users/:id/ban',sameOrigin,auth,owner,async(req,res)=>{if(req.params.id===req.account.id)return fail(res,400,'SELF_ACTION_BLOCKED','Owner tidak dapat memban dirinya sendiri.');const r=await query("UPDATE users SET status='banned',banned_at=now(),ban_reason=$2,updated_at=now() WHERE id=$1 RETURNING id,status",[req.params.id,String(req.body?.reason||'Dibatasi owner').slice(0,500)]);if(!r.length)return fail(res,404,'NOT_FOUND','User tidak ditemukan.');await audit.writeAudit({actorUserId:req.account.id,action:'user_ban',targetType:'user',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true,user:r[0]});});
router.post('/owner/users/:id/approve',sameOrigin,auth,owner,async(req,res)=>{const r=await query("UPDATE users SET status='active',updated_at=now() WHERE id=$1 AND status='pending' RETURNING id,status",[req.params.id]);if(!r.length)return fail(res,404,'NOT_FOUND','User pending tidak ditemukan.');await audit.writeAudit({actorUserId:req.account.id,action:'user_approve',targetType:'user',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true,user:r[0]});});
router.post('/owner/users/:id/unban',sameOrigin,auth,owner,async(req,res)=>{const r=await query("UPDATE users SET status='active',banned_at=NULL,ban_reason=NULL,updated_at=now() WHERE id=$1 AND lower(email)<>lower($2) RETURNING id,status",[req.params.id,process.env.OWNER_EMAIL||'']);if(!r.length)return fail(res,404,'NOT_FOUND','User tidak ditemukan atau tindakan ditolak.');await audit.writeAudit({actorUserId:req.account.id,action:'user_unban',targetType:'user',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true,user:r[0]});});
router.patch('/owner/users/:id/tier',sameOrigin,auth,owner,async(req,res)=>{const tier=String(req.body?.tier||'').toUpperCase();if(!['FREE','SULTAN','SEPUH','DEWA'].includes(tier))return fail(res,400,'INVALID_TIER','Tier tidak valid.');const r=await query('UPDATE users SET tier=$2,updated_at=now() WHERE id=$1 AND lower(email)<>lower($3) RETURNING id,tier',[req.params.id,tier,process.env.OWNER_EMAIL||'']);if(!r.length)return fail(res,404,'NOT_FOUND','User tidak ditemukan atau tindakan ditolak.');await audit.writeAudit({actorUserId:req.account.id,action:'user_tier_change',targetType:'user',targetId:req.params.id,metadata:{tier},ipAddress:ip(req)});res.json({success:true,user:r[0]});});
router.delete('/owner/users/:id',sameOrigin,auth,owner,async(req,res)=>{if(req.params.id===req.account.id)return fail(res,400,'SELF_ACTION_BLOCKED','Owner tidak dapat menghapus dirinya sendiri.');await query('DELETE FROM users WHERE id=$1 AND lower(email)<>lower($2)',[req.params.id,process.env.OWNER_EMAIL||'']);await audit.writeAudit({actorUserId:req.account.id,action:'user_delete',targetType:'user',targetId:req.params.id,ipAddress:ip(req)});res.json({success:true});});
router.get('/owner/payments',auth,owner,async(req,res)=>{await orderService.expirePendingOrders();res.json({success:true,payments:await query('SELECT p.*,o.order_code,o.tier,u.email,u.name FROM payments p JOIN orders o ON o.id=p.order_id JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC LIMIT 250')});});
async function settleManual(req,res,approve){const paymentId=req.params.id;try{const row=await query(`WITH candidate AS (SELECT p.id,p.order_id,p.user_id,p.amount,o.tier FROM payments p JOIN orders o ON o.id=p.order_id WHERE p.id=$1 AND p.provider='manual' AND p.status='pending' AND o.status='pending' FOR UPDATE), upd_p AS (UPDATE payments p SET status=$2,verified_at=CASE WHEN $2='paid' THEN now() ELSE NULL END,updated_at=now() FROM candidate c WHERE p.id=c.id RETURNING p.id,p.order_id,p.user_id), upd_o AS (UPDATE orders o SET status=$2,paid_at=CASE WHEN $2='paid' THEN now() ELSE NULL END,updated_at=now() FROM upd_p p WHERE o.id=p.order_id RETURNING o.user_id,o.tier,o.id), upd_u AS (UPDATE users u SET tier=CASE WHEN $2='paid' AND (CASE u.tier WHEN 'OWNER' THEN 4 WHEN 'DEWA' THEN 3 WHEN 'SEPUH' THEN 2 WHEN 'SULTAN' THEN 1 ELSE 0 END)<(CASE upd_o.tier WHEN 'DEWA' THEN 3 WHEN 'SEPUH' THEN 2 ELSE 1 END) THEN upd_o.tier ELSE u.tier END,updated_at=now() FROM upd_o WHERE u.id=upd_o.user_id RETURNING u.id) INSERT INTO audit_logs(actor_user_id,action,target_type,target_id,metadata,ip_address) SELECT $3,$4,'payment',$1,jsonb_build_object('decision',$2),$5::inet FROM upd_u RETURNING id`,[paymentId,approve?'paid':'rejected',req.account.id,approve?'payment_approve':'payment_reject',ip(req)]);if(!row.length)return fail(res,409,'PAYMENT_NOT_PENDING','Pembayaran tidak pending atau sudah diproses.');res.json({success:true,status:approve?'paid':'rejected'});}catch{fail(res,503,'SETTLEMENT_FAILED','Perubahan pembayaran gagal.');}}
router.post('/owner/payments/:id/approve',sameOrigin,auth,owner,(req,res)=>settleManual(req,res,true));router.post('/owner/payments/:id/reject',sameOrigin,auth,owner,(req,res)=>settleManual(req,res,false));
router.get('/owner/server',auth,owner,async(req,res)=>{const r=await query('SELECT maintenance_enabled,maintenance_message,updated_at FROM server_settings WHERE id=1');res.json({success:true,settings:r[0]});});
router.patch('/owner/server',sameOrigin,auth,owner,async(req,res)=>{const enabled=!!req.body?.maintenance_enabled;const message=String(req.body?.maintenance_message||'Yannz API sedang dalam maintenance.').slice(0,500);const r=await query('UPDATE server_settings SET maintenance_enabled=$1,maintenance_message=$2,updated_at=now(),updated_by=$3 WHERE id=1 RETURNING *',[enabled,message,req.account.id]);await audit.writeAudit({actorUserId:req.account.id,action:'maintenance_change',targetType:'server_settings',metadata:{enabled},ipAddress:ip(req)});res.json({success:true,settings:r[0]});});
router.get('/owner/audit',auth,owner,async(req,res)=>res.json({success:true,logs:await query('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 300')}));
router.get('/owner/backup',auth,owner,async(req,res)=>{try{const names=['users','api_keys','endpoints','orders','payments','audit_logs','server_settings'];const backup={generatedAt:new Date().toISOString(),version:1,data:{}};for(const table of names){backup.data[table]=await query(table==='api_keys'?'SELECT id,user_id,name,key_hash,key_prefix,status,last_used_at,created_at,revoked_at FROM api_keys':`SELECT * FROM ${table}`);}await audit.writeAudit({actorUserId:req.account.id,action:'backup_create',targetType:'backup',ipAddress:ip(req)});res.setHeader('Content-Disposition',`attachment; filename="yannz-api-backup-${new Date().toISOString().slice(0,10)}.json"`);res.json(backup);}catch{fail(res,503,'BACKUP_FAILED','Backup tidak dapat dibuat.');}});
router.get('/owner',auth,owner,(req,res)=>res.sendFile(require('path').join(__dirname,'..','views','owner.html')));
router.get('/owner/dashboard',auth,owner,async(req,res)=>{await audit.writeAudit({actorUserId:req.account.id,action:'owner_access',targetType:'owner_dashboard',ipAddress:ip(req)}).catch(()=>{});const r=await query(`SELECT (SELECT count(*)::int FROM users) users,(SELECT count(*)::int FROM users WHERE status='active') active_users,(SELECT count(*)::int FROM users WHERE status='banned') banned_users,(SELECT count(*)::int FROM users WHERE tier='FREE') free,(SELECT count(*)::int FROM users WHERE tier='SULTAN') sultan,(SELECT count(*)::int FROM users WHERE tier='SEPUH') sepuh,(SELECT count(*)::int FROM users WHERE tier='DEWA') dewa,(SELECT COALESCE(sum(request_count),0)::int FROM api_usage WHERE usage_date=(now() AT TIME ZONE 'UTC')::date) requests_today,(SELECT count(*)::int FROM payments) payments,(SELECT count(*)::int FROM payments WHERE status='pending') pending_payments,(SELECT COALESCE(sum(amount),0)::int FROM payments WHERE status='paid') revenue,(SELECT count(*)::int FROM endpoints WHERE status='active') active_endpoints,(SELECT count(*)::int FROM endpoints WHERE locked) locked_endpoints`);res.json({success:true,stats:r[0]});});
router.post('/webhooks/pakasir',async(req,res)=>{try{const b=req.body||{};const code=String(b.order_id||'');const amount=Number(b.amount);if(!code||!Number.isFinite(amount)||!process.env.PAKASIR_PROJECT||String(b.project||'')!==process.env.PAKASIR_PROJECT||String(b.status||'').toLowerCase()!=='completed')return fail(res,400,'INVALID_WEBHOOK','Payload transaksi tidak valid.');const o=(await query('SELECT * FROM orders WHERE order_code=$1',[code]))[0];if(!o||Number(o.amount)!==amount)return fail(res,400,'ORDER_MISMATCH','Order atau nominal tidak cocok.');if(o.status==='paid')return res.json({success:true,processed:false,duplicate:true});if(o.status!=='pending')return fail(res,409,'ORDER_NOT_PENDING','Order tidak lagi pending.');if(!await pakasir.verifyTransaction(code,amount))return fail(res,202,'PAYMENT_UNVERIFIED','Transaksi belum terverifikasi oleh provider.');const tx=await query(`WITH upd_p AS (UPDATE payments SET status='paid',verified_at=now(),updated_at=now() WHERE order_id=$1 AND provider='pakasir' AND status='pending' RETURNING id,order_id,user_id), upd_o AS (UPDATE orders SET status='paid',paid_at=now(),updated_at=now() WHERE id=$1 AND status='pending' AND EXISTS(SELECT 1 FROM upd_p) RETURNING user_id,tier,id), upd_u AS (UPDATE users u SET tier=CASE WHEN (CASE u.tier WHEN 'OWNER' THEN 4 WHEN 'DEWA' THEN 3 WHEN 'SEPUH' THEN 2 WHEN 'SULTAN' THEN 1 ELSE 0 END)<(CASE upd_o.tier WHEN 'DEWA' THEN 3 WHEN 'SEPUH' THEN 2 ELSE 1 END) THEN upd_o.tier ELSE u.tier END,updated_at=now() FROM upd_o WHERE u.id=upd_o.user_id RETURNING u.id) INSERT INTO audit_logs(action,target_type,target_id,metadata) SELECT 'pakasir_webhook_paid','order',$1,jsonb_build_object('amount',$2) FROM upd_u RETURNING id`,[o.id,amount]);return res.json({success:true,processed:!!tx.length});}catch{fail(res,503,'WEBHOOK_PROCESSING_FAILED','Webhook belum dapat diproses.');}});
for (const layer of router.stack) { if (layer.route) for (const routeLayer of layer.route.stack) { const original=routeLayer.handle; routeLayer.handle=(req,res,next)=>Promise.resolve(original(req,res,next)).catch(next); } }
router.use((err,req,res,next)=>{console.error('Platform route failed:',err?.code||'PLATFORM_ERROR');if(res.headersSent)return next(err);return fail(res,500,'INTERNAL_ERROR','Terjadi kesalahan server.');});
module.exports=router;
