'use strict';
// Endpoints from Dongtube API (https://api.dongtube.id/docs), proxied through lib/apiproxy.js.
// The key is DONGTUBE_API_KEY in Vercel (config/apiServers.js), never in the repo. Endpoints marked
// keyOptional are public on Dongtube and also work while the key isn't set.
//
// Endpoints that do the same as one the site already has (or as another Dongtube endpoint) are
// backupOnly: they're not listed on their own, the site switches to them when the main one breaks
// (config/endpointGroups.js). Their path is /api/dongtube/<Dongtube path>.
//
// Left out on purpose:
//   - /tools/vccgen: nomor kartu kredit.
//   - /tools/fakedata: identitas palsu lengkap dengan foto.
//   - /canvas/fake-dana: bukti saldo DANA palsu (penipuan).
//   - /canvas/fake-ovo: bukti saldo OVO palsu (penipuan).
//   - /canvas/fake-ff: keluarga "fake" akun.
//   - /canvas/fake-tele: profil Telegram palsu orang lain.
//   - /canvas/fake-ch: saluran WhatsApp palsu.
//   - /canvas/post-ig: postingan Instagram palsu.
//   - /canvas/news: screenshot berita palsu.
//   - /canvas/fake-call: fake call udah ada (/api/maker/fakecall).
//   - /canvas/fake-call-andro: fake call udah ada (/api/maker/fakecall).
//   - /get/pp-wa: ambil foto orang dari nomor HP (doxxing).
//   - /tools/nik-parser: data pribadi dari NIK.
//   - /check/npwp: data pribadi dari NPWP.
//   - /tools/ngl: kirim pesan anonim (spam).
//   - /tools/am-premium: akses premium Alight Motion tanpa bayar.
//   - /canvas/system-info: info server Dongtube sendiri.
//   - /dynamic/hello: endpoint tes.
//   - /tools/voices: cuma daftar suara buat edge-tts.
//
// Generated from the docs page; edit freely.
const { makeEndpoint } = require('../lib/apiproxy');
const { checkSampleImage } = require('../lib/theresav');
// Sample photo for the automatic endpoint check (the real request uses the caller's own image).
const IMG = checkSampleImage();

const SPECS = [

  // ---------------------------------------------------------------- AI
  { server: 'dongtube', category: 'AI', name: 'Asyntai AI', desc: 'Ngobrol sama AI Asyntai pakai bahasa Indonesia.', path: '/api/ai/asynt', upstream: '/ai/asynt', params: [{ name: 'text', required: true, placeholder: 'halo apa kabar' }, { name: 'sessionId', required: false, placeholder: 'ID sesi (agar konteks nyambung)' }], sample: { text: 'halo apa kabar' } },
  { server: 'dongtube', category: 'AI', name: 'DeepAI Chat', desc: 'Ngobrol sama chatbot DeepAI.', path: '/api/ai/deepai', upstream: '/ai/deepai', params: [{ name: 'text', required: true, placeholder: 'ceritakan kisah singkat tentang petualangan di luar angkasa' }, { name: 'model', required: false, placeholder: 'Model DeepAI', options: ['standard', 'fast', 'creative', 'casual'] }], sample: { text: 'Halo' } },
  { server: 'dongtube', category: 'AI', name: 'Gandalf AI', desc: 'Ngobrol sama AI asisten berbahasa Indonesia.', path: '/api/ai/gandalf', upstream: '/ai/gandalf', params: [{ name: 'q', required: true, placeholder: 'Pertanyaan/pesan' }], sample: { q: 'Halo' } },
  { server: 'dongtube', category: 'AI', name: 'Nano Banana Edit', desc: 'Edit gambar pakai AI Nano Banana: edit, hapus background/objek/watermark, pertajam, perbesar.', path: '/api/ai/nano-banana', upstream: '/ai/nano-banana', fileUrl: { param: 'image_url', accept: 'image/*', required: true }, params: [{ name: 'image_url', required: true, placeholder: 'URL gambar yang akan diedit' }, { name: 'prompt', required: true, placeholder: 'Change the sky to a sunset' }, { name: 'mode', required: false, placeholder: 'Mode operasi', options: ['edit', 'remove_bg', 'remove_object', 'remove_watermark', 'sharpen', 'upscale', 'extend', 'poster', 'cartoon', 'passport'] }], sample: { image_url: IMG, prompt: 'Change the sky to a sunset' } },
  { server: 'dongtube', category: 'AI', name: 'Pollinations Image', desc: 'Bikin gambar dari teks pakai AI.', path: '/api/ai/pollinations', upstream: '/ai/pollinations', params: [{ name: 'prompt', required: true, placeholder: 'cute cat with sword' }, { name: 'width', required: false, placeholder: 'Lebar (256–1792)' }, { name: 'height', required: false, placeholder: 'Tinggi (256–1024)' }], sample: { prompt: 'cute cat with sword' } },
  { server: 'dongtube', category: 'AI', name: 'Figurine Generator', desc: 'Bikin gambar figurine 1/7 ala BANDAI dari deskripsi karakter.', path: '/api/ai/text-to-image', upstream: '/ai/text-to-image', params: [{ name: 'name', required: true, placeholder: 'Nama/deskripsi karakter' }], sample: { name: 'kucing samurai' } },

  // ---------------------------------------------------------------- Anime
  { server: 'dongtube', category: 'Anime', name: 'Anichin Detail', desc: 'Ambil detail dan daftar episode anime dari Anichin.moe.', path: '/api/anime/anichin/detail', upstream: '/anime/anichin/detail', params: [{ name: 'url', required: true, placeholder: '/keyboard-immortal/' }], sample: { url: '/keyboard-immortal/' } },
  { server: 'dongtube', category: 'Anime', name: 'Anichin Latest', desc: 'Ambil anime terbaru dari Anichin.moe.', path: '/api/anime/anichin/latest', upstream: '/anime/anichin/latest', params: [{ name: 'page', required: false, placeholder: 'Halaman' }] },
  { server: 'dongtube', category: 'Anime', name: 'Anichin Search', desc: 'Cari anime/donghua dari Anichin.moe.', path: '/api/anime/anichin/search', upstream: '/anime/anichin/search', params: [{ name: 'q', required: true, placeholder: 'immortality' }], sample: { q: 'immortality' } },
  { server: 'dongtube', category: 'Anime', name: 'Kiryuu Manga Search', desc: 'Search manga di Kiryuu.', path: '/api/anime/kiryuu/search', upstream: '/anime/kiryuu/search', params: [{ name: 'q', required: true, placeholder: 'Kata kunci manga' }], sample: { q: 'solo leveling' } },
  { server: 'dongtube', category: 'Anime', name: 'Oploverz Ongoing', desc: 'Daftar anime ongoing Oploverz.', path: '/api/anime/oploverz/ongoing', upstream: '/anime/oploverz/ongoing', params: [{ name: 'page', required: false, placeholder: 'Halaman' }] },
  { server: 'dongtube', category: 'Anime', name: 'Oploverz Search', desc: 'Cari anime di Oploverz.', path: '/api/anime/oploverz/search', upstream: '/anime/oploverz/search', params: [{ name: 'q', required: true, placeholder: 'Kata kunci anime' }], sample: { q: 'one piece' } },
  { server: 'dongtube', category: 'Anime', name: 'KomikIndo', desc: 'Manga/manhwa dari KomikIndo: terbaru, cari, genre, detail.', path: '/api/manga/komikindo', upstream: '/manga/komikindo', params: [{ name: 'action', required: false, placeholder: 'Aksi', options: ['latest', 'rekomendasi', 'terpopuler', 'search', 'genre', 'theme', 'type', 'detail'] }, { name: 'q', required: false, placeholder: 'Kata kunci (action=search)' }, { name: 'genre', required: false, placeholder: 'Genre (action=genre)', options: ['action', 'adventure', 'comedy', 'drama', 'fantasy', 'horror', 'isekai', 'mecha', 'mystery', 'psychological', 'romance', 'sci-fi', 'slice-of-life', 'sports', 'supernatural', 'thriller'] }, { name: 'type', required: false, placeholder: 'Tipe (action=type)', options: ['manga', 'manhua', 'manhwa'] }, { name: 'url', required: false, placeholder: 'URL manga (action=detail)' }, { name: 'page', required: false, placeholder: 'Halaman' }] },

  // ---------------------------------------------------------------- Canvas
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card', desc: 'Gambar perpisahan member ala Discord.', path: '/api/canvas/goodbye', upstream: '/canvas/goodbye', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: false, placeholder: 'Member count' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card v1', desc: 'Gambar perpisahan member, gaya sedih.', path: '/api/canvas/goodbyev1', upstream: '/canvas/goodbyev1', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: false, placeholder: 'Member count' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card v2', desc: 'Gambar perpisahan member, gaya gradien.', path: '/api/canvas/goodbyev2', upstream: '/canvas/goodbyev2', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card v3', desc: 'Gambar perpisahan member, gaya neon gelap.', path: '/api/canvas/goodbyev3', upstream: '/canvas/goodbyev3', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card v4', desc: 'Gambar perpisahan member, gaya minimalis.', path: '/api/canvas/goodbyev4', upstream: '/canvas/goodbyev4', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Goodbye Card v5', desc: 'Gambar perpisahan member, gradien ungu.', path: '/api/canvas/goodbyev5', upstream: '/canvas/goodbyev5', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'guildName', required: true, placeholder: 'Guild name' }], sample: { username: 'Yannz', avatar: IMG, guildName: 'Yannz API' } },
  { server: 'dongtube', category: 'Canvas', name: 'Instagram Quote Chat', desc: 'Gambar quote DM Instagram.', path: '/api/canvas/igqc', upstream: '/canvas/igqc', params: [{ name: 'text', required: false, placeholder: 'Teks quote (atau image saja)' }, { name: 'image', required: false, placeholder: 'URL gambar dalam bubble' }], sample: { text: 'halo' } },
  { server: 'dongtube', category: 'Canvas', name: 'iPhone Quote Chat', desc: 'Gambar quote chat iPhone.', path: '/api/canvas/iqc', upstream: '/canvas/iqc', params: [{ name: 'text', required: true, placeholder: 'Kesendirian adalah teman terbaik ku😂' }, { name: 'time', required: false, placeholder: '22.54' }], sample: { text: 'halo' } },
  { server: 'dongtube', category: 'Canvas', name: 'Kalender', desc: 'Gambar kalender Indonesia lengkap sama tanggal merahnya.', path: '/api/canvas/kalender', upstream: '/canvas/kalender', params: [{ name: 'year', required: false, placeholder: '2026' }, { name: 'month', required: false, placeholder: 'Bulan (kosongkan = 12 bulan penuh)', options: ['januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember'] }] },
  { server: 'dongtube', category: 'Canvas', name: 'Meme You\'re Beautiful', desc: 'Meme \'You\'re Beautiful\' pakai gambar sendiri.', path: '/api/canvas/meme-beautiful', upstream: '/canvas/meme-beautiful', params: [{ name: 'image1', required: true, placeholder: 'URL gambar atas' }, { name: 'image2', required: false, placeholder: 'URL gambar bawah (default sama dengan image1)' }], sample: { image1: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Meme Drake', desc: 'Meme Drake: nggak suka vs suka.', path: '/api/canvas/meme-drake', upstream: '/canvas/meme-drake', params: [{ name: 'text1', required: true, placeholder: 'Femboy' }, { name: 'text2', required: true, placeholder: 'Tomboy' }], sample: { text1: 'Begadang', text2: 'Tidur cepat' } },
  { server: 'dongtube', category: 'Canvas', name: 'Meme Jarvis', desc: 'Meme \'Jarvis, tolong…\'.', path: '/api/canvas/meme-jarvis', upstream: '/canvas/meme-jarvis', params: [{ name: 'text', required: true, placeholder: 'Jarvis, tolong diapakan dulu…' }], sample: { text: 'Jarvis, rapihin kodenya' } },
  { server: 'dongtube', category: 'Canvas', name: 'Meme Two Buttons', desc: 'Meme dua tombol: kiri vs kanan.', path: '/api/canvas/meme-twobuttons', upstream: '/canvas/meme-twobuttons', params: [{ name: 'text1', required: true, placeholder: 'Tidur' }, { name: 'text2', required: true, placeholder: 'Scrolling' }], sample: { text1: 'Tidur', text2: 'Scrolling' } },
  { server: 'dongtube', category: 'Canvas', name: 'Pixel Art', desc: 'Ubah gambar jadi pixel art.', path: '/api/canvas/pixel-art', upstream: '/canvas/pixel-art', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar yang mau di-pixelate' }, { name: 'grid', required: false, placeholder: 'Ketajaman pixel (lebih kecil = lebih kotak)', options: ['32', '48', '64', '96'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Profile Card', desc: 'Kartu profil member ala Discord.', path: '/api/canvas/profile', upstream: '/canvas/profile', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'level', required: false, placeholder: 'Level' }, { name: 'exp', required: false, placeholder: 'Current EXP' }, { name: 'requiredExp', required: false, placeholder: 'Required EXP' }, { name: 'rank', required: false, placeholder: 'Rank' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', avatar: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'WhatsApp Quote Chat', desc: 'Gambar quote chat WhatsApp (gelap/terang).', path: '/api/canvas/qcwa', upstream: '/canvas/qcwa', params: [{ name: 'username', required: false, placeholder: '~ Someone' }, { name: 'phone', required: false, placeholder: '62 8xx-xxxx-xxxx' }, { name: 'tag', required: false, placeholder: 'Tag/bio kecil' }, { name: 'pp', required: true, placeholder: 'URL foto profil' }, { name: 'text', required: false, placeholder: 'Teks quote' }, { name: 'image', required: false, placeholder: 'URL gambar dalam bubble' }, { name: 'mode', required: false, placeholder: 'Tema', options: ['dark', 'light'] }], sample: { pp: IMG, text: 'halo' } },
  { server: 'dongtube', category: 'Canvas', name: 'Rank Up Card', desc: 'Gambar naik rank.', path: '/api/canvas/rankup', upstream: '/canvas/rankup', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'oldRank', required: true, placeholder: 'Old rank' }, { name: 'newRank', required: true, placeholder: 'New rank' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', avatar: IMG, oldRank: '1', newRank: '2' } },
  { server: 'dongtube', category: 'Canvas', name: 'Ship Card', desc: 'Gambar kecocokan dua orang (ship).', path: '/api/canvas/ship', upstream: '/canvas/ship', params: [{ name: 'avatar1', required: true, placeholder: 'Avatar 1 URL' }, { name: 'avatar2', required: true, placeholder: 'Avatar 2 URL' }, { name: 'percentage', required: false, placeholder: 'Love %' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { avatar1: IMG, avatar2: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Meme Timpa Teks', desc: 'Meme tulisan di kertas kecil.', path: '/api/canvas/timpa-teks', upstream: '/canvas/timpa-teks', params: [{ name: 'username', required: false, placeholder: 'Rin' }, { name: 'text', required: true, placeholder: 'Katanya just friend kok manggil sayang' }], sample: { text: 'halo' } },
  { server: 'dongtube', category: 'Canvas', name: 'TikTok Quote Chat', desc: 'Gambar quote chat TikTok.', path: '/api/canvas/ttqc', upstream: '/canvas/ttqc', params: [{ name: 'username', required: false, placeholder: 'Nama tampilan' }, { name: 'text', required: true, placeholder: 'Just friend kok cemburu 😂' }, { name: 'avatar', required: false, placeholder: 'URL avatar' }], sample: { text: 'halo' } },
  { server: 'dongtube', category: 'Canvas', name: 'Welcome Card', desc: 'Gambar sambutan member baru ala Discord.', path: '/api/canvas/welcome', upstream: '/canvas/welcome', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'guildName', required: true, placeholder: 'Guild/server name' }, { name: 'memberCount', required: true, placeholder: 'Member count' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'background', required: false, placeholder: 'Background URL' }, { name: 'guildIcon', required: false, placeholder: 'Guild icon URL' }], sample: { username: 'Yannz', guildName: 'Yannz API', memberCount: '100', avatar: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Welcome Card v2', desc: 'Gambar sambutan member baru, versi ringkas.', path: '/api/canvas/welcomev2', upstream: '/canvas/welcomev2', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: true, placeholder: 'Member count' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', guildName: 'Yannz API', memberCount: '100', avatar: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Welcome Card v3', desc: 'Gambar sambutan member baru, gaya gradien.', path: '/api/canvas/welcomev3', upstream: '/canvas/welcomev3', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: true, placeholder: 'Member count' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }], sample: { username: 'Yannz', guildName: 'Yannz API', memberCount: '100', avatar: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Welcome Card v4', desc: 'Gambar sambutan member baru, mode gelap.', path: '/api/canvas/welcomev4', upstream: '/canvas/welcomev4', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: true, placeholder: 'Member count' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }, { name: 'background', required: false, placeholder: 'Background URL' }], sample: { username: 'Yannz', guildName: 'Yannz API', memberCount: '100', avatar: IMG } },
  { server: 'dongtube', category: 'Canvas', name: 'Welcome Card v5', desc: 'Gambar sambutan member baru, gaya neon.', path: '/api/canvas/welcomev5', upstream: '/canvas/welcomev5', params: [{ name: 'username', required: true, placeholder: 'Username' }, { name: 'guildName', required: true, placeholder: 'Guild name' }, { name: 'memberCount', required: true, placeholder: 'Member count' }, { name: 'avatar', required: true, placeholder: 'Avatar URL' }], sample: { username: 'Yannz', guildName: 'Yannz API', memberCount: '100', avatar: IMG } },

  // ---------------------------------------------------------------- Check
  { server: 'dongtube', category: 'Check', name: 'Cek Akun MLBB', desc: 'Cek akun Mobile Legends: nickname, status first recharge, region.', path: '/api/check/mlbb', upstream: '/cek/mlbb', params: [{ name: 'uid', required: true, placeholder: '1422073161' }, { name: 'zone', required: true, placeholder: '15910' }], sample: { uid: '1422073161', zone: '15910' } },

  // ---------------------------------------------------------------- Downloader
  { server: 'dongtube', category: 'Downloader', name: 'iQIYI Detail', desc: 'Detail dan daftar episode album iQIYI.', path: '/api/detail/iqiyi', upstream: '/detail/iqiyi', params: [{ name: 'slug', required: true, placeholder: 'forging-justice-2026-x5mka524ph' }], sample: { slug: 'forging-justice-2026-x5mka524ph' } },
  { server: 'dongtube', category: 'Downloader', name: 'Bilibili Downloader', desc: 'Download video dari Bilibili (bilibili.tv).', path: '/api/download/bilibili', upstream: '/download/bilibili', params: [{ name: 'url', required: true, placeholder: 'URL video Bilibili' }, { name: 'quality', required: false, placeholder: 'Kualitas video', options: ['360P', '480P', '720P'] }] },
  { server: 'dongtube', category: 'Downloader', name: 'Google Drive Downloader', desc: 'Info & direct link file publik Google Drive.', path: '/api/download/gdrive', upstream: '/download/gdrive', params: [{ name: 'url', required: true, placeholder: 'URL / ID file Drive' }] },
  { server: 'dongtube', category: 'Downloader', name: 'GitHub Downloader', desc: 'Download repo GitHub jadi ZIP, atau file-nya langsung.', path: '/api/download/github', upstream: '/download/github', params: [{ name: 'url', required: true, placeholder: 'URL file/repo GitHub' }], sample: { url: 'https://github.com/expressjs/cors' } },
  { server: 'dongtube', category: 'Downloader', name: 'Lahelu Downloader', desc: 'Ambil media & info post Lahelu.com.', path: '/api/download/lahelu', upstream: '/download/lahelu', params: [{ name: 'url', required: true, placeholder: 'URL / ID post Lahelu' }] },
  { server: 'dongtube', category: 'Downloader', name: 'NPM Package Downloader', desc: 'Download paket npm jadi file .tgz.', path: '/api/download/npm', upstream: '/download/npm', params: [{ name: 'package', required: true, placeholder: 'express' }, { name: 'version', required: false, placeholder: 'Versi spesifik (default latest)' }], sample: { package: 'cors' } },
  { server: 'dongtube', category: 'Downloader', name: 'SoundCloud Downloader', desc: 'Download lagu dari SoundCloud (MP3).', path: '/api/download/soundcloud', upstream: '/download/soundcloud', params: [{ name: 'url', required: true, placeholder: 'URL track/playlist SoundCloud' }] },

  // ---------------------------------------------------------------- Fun
  { server: 'dongtube', category: 'Fun', name: 'Teks Alay', desc: 'Ubah teks jadi gaya alay.', path: '/api/fun/alay', upstream: '/fun/alay', params: [{ name: 'text', required: true, placeholder: 'Teks yang akan dikonversi' }], sample: { text: 'halo semua' } },
  { server: 'dongtube', category: 'Fun', name: 'Fancy Text', desc: 'Ubah teks jadi 40+ gaya font unik.', path: '/api/fun/fancytext', upstream: '/fun/fancytext', params: [{ name: 'text', required: true, placeholder: 'halo' }], sample: { text: 'halo' } },
  { server: 'dongtube', category: 'Fun', name: 'Nama Samaran', desc: 'Nama samaran acak.', path: '/api/fun/nomin', upstream: '/fun/nomin', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Fun', name: 'Fakta Umur', desc: 'Fakta seru dari tanggal lahir: umur detail, statistik, dan lain-lain.', path: '/api/fun/umur', upstream: '/fun/umur', params: [{ name: 'birthdate', required: true, placeholder: '2000-01-15' }], sample: { birthdate: '2000-01-15' } },

  // ---------------------------------------------------------------- Games
  { server: 'dongtube', category: 'Games', name: 'Blue Archive Database', desc: 'Database karakter Blue Archive.', path: '/api/game/bluearchive', upstream: '/game/bluearchive', params: [{ name: 'action', required: false, placeholder: 'Aksi', options: ['list', 'search'] }, { name: 'q', required: false, placeholder: 'Nama karakter (action=search)' }] },
  { server: 'dongtube', category: 'Games', name: 'Asah Otak', desc: 'Asah Otak kuis acak.', path: '/api/games/asahotak', upstream: '/games/asahotak', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Cak Lontong', desc: 'Cak Lontong kuis acak.', path: '/api/games/caklontong', upstream: '/games/caklontong', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Cerdas Cermat SD', desc: 'Kuis cc-sd.', path: '/api/games/cc-sd', upstream: '/games/cc-sd', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Family 100', desc: 'Family 100 quiz.', path: '/api/games/family100', upstream: '/games/family100', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Lengkapi Kalimat', desc: 'Kuis lengkapikalimat.', path: '/api/games/lengkapikalimat', upstream: '/games/lengkapikalimat', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Math Quiz', desc: 'Kuis math-quiz.', path: '/api/games/math-quiz', upstream: '/games/math-quiz', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Siapa Dia', desc: 'Kuis siapa-dia.', path: '/api/games/siapa-dia', upstream: '/games/siapa-dia', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Susun Kata', desc: 'Game susun kata.', path: '/api/games/susunkata', upstream: '/games/susunkata', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Hewan', desc: 'Kuis tebak-hewan.', path: '/api/games/tebak-hewan', upstream: '/games/tebak-hewan', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kabupaten', desc: 'Kuis tebak-kabupaten.', path: '/api/games/tebak-kabupaten', upstream: '/games/tebak-kabupaten', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kalimat', desc: 'Kuis tebak-kalimat.', path: '/api/games/tebak-kalimat', upstream: '/games/tebak-kalimat', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Karakter FF', desc: 'Kuis tebak-karakter-ff.', path: '/api/games/tebak-karakter-ff', upstream: '/games/tebak-karakter-ff', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kartun', desc: 'Kuis tebak-kartun.', path: '/api/games/tebak-kartun', upstream: '/games/tebak-kartun', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kimia', desc: 'Kuis tebak-kimia.', path: '/api/games/tebak-kimia', upstream: '/games/tebak-kimia', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Lagu', desc: 'Kuis tebak-lagu.', path: '/api/games/tebak-lagu', upstream: '/games/tebak-lagu', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Lirik', desc: 'Kuis tebak-lirik.', path: '/api/games/tebak-lirik', upstream: '/games/tebak-lirik', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Logo', desc: 'Kuis tebak-logo.', path: '/api/games/tebak-logo', upstream: '/games/tebak-logo', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Siapa', desc: 'Kuis tebak-siapa.', path: '/api/games/tebak-siapa', upstream: '/games/tebak-siapa', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Tebak An', desc: 'Kuis tebak-tebakan.', path: '/api/games/tebak-tebakan', upstream: '/games/tebak-tebakan', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Warna', desc: 'Kuis tebak-warna.', path: '/api/games/tebak-warna', upstream: '/games/tebak-warna', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Bendera', desc: 'Game tebak bendera negara.', path: '/api/games/tebakbendera', upstream: '/games/tebakbendera', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Gambar', desc: 'Game tebak gambar.', path: '/api/games/tebakgambar', upstream: '/games/tebakgambar', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Game', desc: 'Game tebak-tebakan seputar game.', path: '/api/games/tebakgame', upstream: '/games/tebakgame', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Hero ML', desc: 'Game tebak hero Mobile Legends.', path: '/api/games/tebakheroml', upstream: '/games/tebakheroml', params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kata', desc: 'Game tebak kata.', path: '/api/games/tebakkata', upstream: '/games/tebakkata', params: [] },

  // ---------------------------------------------------------------- Image
  { server: 'dongtube', category: 'Image', name: 'Image to ASCII', desc: 'Ubah gambar jadi ASCII art.', path: '/api/tools/image-ascii', upstream: '/tools/image-ascii', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar sumber' }, { name: 'width', required: false, placeholder: 'Lebar karakter (20-300)' }, { name: 'color', required: false, placeholder: 'Tipe art', options: ['mono', 'color'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Image', name: 'Pixelate', desc: 'Ubah gambar jadi pixel (level 1-40).', path: '/api/imgedit/pixelate', upstream: '/imgedit/pixelate', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'level', required: false, placeholder: '30' }], sample: { url: IMG } },

  // ---------------------------------------------------------------- Info
  { server: 'dongtube', category: 'Info', name: 'Bilibili Info', desc: 'Info video Bilibili + URL download.', path: '/api/info/bilibili', upstream: '/info/bilibili', params: [{ name: 'url', required: true, placeholder: 'URL video Bilibili' }] },
  { server: 'dongtube', category: 'Info', name: 'Cuaca BMKG', desc: 'Info cuaca dari BMKG.', path: '/api/info/cuaca/v1', upstream: '/info/cuaca/v1', keyOptional: true, params: [{ name: 'area', required: false, placeholder: 'area' }] },
  { server: 'dongtube', category: 'Info', name: 'Cuaca Dunia', desc: 'Cuaca kota di seluruh dunia.', path: '/api/info/cuaca/v2', upstream: '/info/cuaca/v2', params: [{ name: 'kota', required: true, placeholder: 'Nama kota (bahasa Inggris)' }, { name: 'days', required: false, placeholder: 'Prakiraan hari (maks 7)' }], sample: { kota: 'jakarta' } },
  { server: 'dongtube', category: 'Info', name: 'Info Gempa', desc: 'Info gempa terbaru dari BMKG.', path: '/api/info/gempa', upstream: '/info/gempa', params: [{ name: 'type', required: false, placeholder: 'Jenis gempa', options: ['terkini', 'dirasakan', 'autogempa'] }] },
  { server: 'dongtube', category: 'Info', name: 'Stok Grow a Garden', desc: 'Cek stok terbaru game Grow a Garden (Roblox).', path: '/api/info/grow-a-garden', upstream: '/info/grow-a-garden', params: [] },
  { server: 'dongtube', category: 'Info', name: 'Hari Libur', desc: 'Jadwal hari libur nasional.', path: '/api/info/hari-libur', upstream: '/info/hari-libur', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Info', name: 'Jadwal Sholat', desc: 'Jadwal sholat harian & bulanan seluruh Indonesia.', path: '/api/info/jadwal-sholat', upstream: '/info/jadwal-sholat', params: [{ name: 'kota', required: false, placeholder: 'Nama kota atau ID kota (contoh: jakarta, surabaya, bandung, atau 308)' }, { name: 'bulan', required: false, placeholder: '9' }, { name: 'tahun', required: false, placeholder: '2026' }] },
  { server: 'dongtube', category: 'Info', name: 'Jadwal TV', desc: 'Jadwal TV hari ini.', path: '/api/info/jadwaltv', upstream: '/info/jadwaltv', keyOptional: true, params: [] },

  // ---------------------------------------------------------------- Maker
  { server: 'dongtube', category: 'Maker', name: 'Carbon (Code to Image)', desc: 'Ubah kode jadi gambar PNG tema gelap.', path: '/api/maker/carbon', upstream: '/maker/carbon', params: [{ name: 'code', required: true, placeholder: 'Kode yang mau di-screenshot' }, { name: 'lang', required: false, placeholder: 'Bahasa untuk highlight', options: ['javascript', 'typescript', 'python', 'php', 'java', 'go', 'ruby', 'c', 'cpp', 'bash', 'json', 'css', 'html', 'sql'] }], sample: { code: "console.log(\"halo\")" } },
  { server: 'dongtube', category: 'Maker', name: 'Landsat Name', desc: 'Tulis nama kamu pakai foto satelit Landsat NASA.', path: '/api/maker/landsat-name', upstream: '/maker/landsat-name', params: [{ name: 'name', required: true, placeholder: 'Nama (huruf a-z)' }, { name: 'variant', required: false, placeholder: '0' }], sample: { name: 'yannz' } },

  // ---------------------------------------------------------------- Movie
  { server: 'dongtube', category: 'Movie', name: 'LK21 Browse', desc: 'Daftar film LK21 (terbaru/populer).', path: '/api/lk21/browse', upstream: '/lk21/browse', params: [{ name: 'mode', required: false, placeholder: 'Mode daftar film', options: ['latest', 'populer'] }, { name: 'page', required: false, placeholder: 'Nomor halaman' }] },

  // ---------------------------------------------------------------- Music
  { server: 'dongtube', category: 'Music', name: 'Murotal Al-Quran', desc: 'Audio murotal Al-Quran per surat, bisa pilih qari.', path: '/api/audio/murotal', upstream: '/audio/murotal', params: [{ name: 'qari', required: false, placeholder: '1' }, { name: 'surah', required: false, placeholder: '1' }, { name: 'rehost', required: false, placeholder: 'Rehost audio via proxy?', options: ['false', 'true'] }] },

  // ---------------------------------------------------------------- News
  { server: 'dongtube', category: 'News', name: 'Antara News', desc: 'Berita dari antaranews.com.', path: '/api/news/antara', upstream: '/news/antara', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'CNBC Indonesia', desc: 'Berita terbaru dari CNBC Indonesia.', path: '/api/news/cnbc', upstream: '/news/cnbc', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'CNN Indonesia', desc: 'Berita dari CNN Indonesia.', path: '/api/news/cnn', upstream: '/news/cnn', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'JKT48 News', desc: 'Berita JKT48 terbaru.', path: '/api/news/jkt48', upstream: '/news/jkt48', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Kompas', desc: 'Berita dari kompas.com.', path: '/api/news/kompas', upstream: '/news/kompas', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Liputan6', desc: 'Berita terbaru dari Liputan6.', path: '/api/news/liputan6', upstream: '/news/liputan6', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Merdeka', desc: 'Berita terkini dari Merdeka.', path: '/api/news/merdeka', upstream: '/news/merdeka', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Sindonews', desc: 'Berita dari sindonews.com.', path: '/api/news/sindonews', upstream: '/news/sindonews', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Suara', desc: 'Berita dari suara.com.', path: '/api/news/suara', upstream: '/news/suara', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'News', name: 'Tribunnews', desc: 'Berita terbaru dari Tribunnews.', path: '/api/news/tribun', upstream: '/news/tribun', keyOptional: true, params: [] },

  // ---------------------------------------------------------------- Primbon
  { server: 'dongtube', category: 'Primbon', name: 'Arti Nama', desc: 'Cari arti nama berdasarkan numerologi Jawa.', path: '/api/primbon/artinama', upstream: '/primbon/artinama', params: [{ name: 'nama', required: true, placeholder: 'Nama yang ingin dicari artinya' }], sample: { nama: 'budi' } },
  { server: 'dongtube', category: 'Primbon', name: 'Kecocokan Pasangan', desc: 'Cek kecocokan pasangan berdasarkan nama (Neptuni Jawa).', path: '/api/primbon/cocokpasangan', upstream: '/primbon/cocokpasangan', params: [{ name: 'nama1', required: true, placeholder: 'Nama pertama' }, { name: 'nama2', required: true, placeholder: 'Nama kedua' }], sample: { nama1: 'budi', nama2: 'siti' } },
  { server: 'dongtube', category: 'Primbon', name: 'Nomor Hoki', desc: 'Cek nomor HP kamu hoki atau nggak.', path: '/api/primbon/nomorhoki', upstream: '/primbon/nomorhoki', params: [{ name: 'nomor', required: true, placeholder: '081234567890' }], sample: { nomor: '081234567890' } },
  { server: 'dongtube', category: 'Primbon', name: 'Potensi Penyakit', desc: 'Cek potensi penyakit dari tanggal lahir.', path: '/api/primbon/penyakit', upstream: '/primbon/penyakit', params: [{ name: 'tanggal', required: true, placeholder: 'Tanggal lahir (DD-MM-YYYY)' }], sample: { tanggal: '15-01-2000' } },
  { server: 'dongtube', category: 'Primbon', name: 'Ramalan Jodoh Bali', desc: 'Ramalan kecocokan jodoh metode Bali.', path: '/api/primbon/ramalan-jodoh-bali', upstream: '/primbon/ramalan-jodoh-bali', params: [{ name: 'nama1', required: true, placeholder: 'Nama pertama' }, { name: 'tgl1', required: true, placeholder: 'Tanggal lahir 1 (DD)' }, { name: 'bln1', required: true, placeholder: 'Bulan lahir 1 (MM)' }, { name: 'thn1', required: true, placeholder: 'Tahun lahir 1 (YYYY)' }, { name: 'nama2', required: true, placeholder: 'Nama kedua' }, { name: 'tgl2', required: true, placeholder: 'Tanggal lahir 2 (DD)' }, { name: 'bln2', required: true, placeholder: 'Bulan lahir 2 (MM)' }, { name: 'thn2', required: true, placeholder: 'Tahun lahir 2 (YYYY)' }], sample: { nama1: 'budi', tgl1: '15', bln1: '01', thn1: '2000', nama2: 'siti', tgl2: '20', bln2: '05', thn2: '2001' } },
  { server: 'dongtube', category: 'Primbon', name: 'Ramal Jodoh', desc: 'Ramal jodoh berdasarkan nama (Neptuni Jawa).', path: '/api/primbon/ramaljodoh', upstream: '/primbon/ramaljodoh', params: [{ name: 'nama1', required: true, placeholder: 'Nama pertama' }, { name: 'nama2', required: true, placeholder: 'Nama kedua' }], sample: { nama1: 'budi', nama2: 'siti' } },
  { server: 'dongtube', category: 'Primbon', name: 'Rezeki & Hoki', desc: 'Cek rejeki dan hoki berdasarkan weton lahir.', path: '/api/primbon/rezeki-hoki', upstream: '/primbon/rezeki-hoki', params: [{ name: 'tanggal', required: true, placeholder: 'Tanggal lahir (DD-MM-YYYY)' }], sample: { tanggal: '15-01-2000' } },
  { server: 'dongtube', category: 'Primbon', name: 'Sifat Usaha', desc: 'Cek sifat usaha/bisnis berdasarkan tanggal lahir.', path: '/api/primbon/sifat-usaha', upstream: '/primbon/sifat-usaha', params: [{ name: 'tanggal', required: true, placeholder: 'Tanggal lahir (DD-MM-YYYY)' }], sample: { tanggal: '15-01-2000' } },
  { server: 'dongtube', category: 'Primbon', name: 'Tafsir Mimpi', desc: 'Tafsir mimpi dari primbon Jawa.', path: '/api/primbon/tafsir-mimpi', upstream: '/primbon/tafsir-mimpi', params: [{ name: 'mimpi', required: true, placeholder: 'Mimpi yang ingin ditafsirkan' }], sample: { mimpi: 'ular' } },
  { server: 'dongtube', category: 'Primbon', name: 'Zodiak', desc: 'Cek zodiak dari tanggal lahir.', path: '/api/primbon/zodiac', upstream: '/primbon/zodiac', params: [{ name: 'tanggal', required: true, placeholder: 'Tanggal lahir (DD-MM-YYYY)' }], sample: { tanggal: '15-01-2000' } },

  // ---------------------------------------------------------------- Random
  { server: 'dongtube', category: 'Random', name: 'Anime Quote', desc: 'Quote anime acak.', path: '/api/random/anime-quote', upstream: '/random/anime-quote', params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Anjing', desc: 'Foto anjing.', path: '/api/random/anjing', upstream: '/random/anjing', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Cerpen', desc: 'Cerpen (cerita pendek).', path: '/api/random/cerpen', upstream: '/random/cerpen', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Fakta', desc: 'Fakta unik.', path: '/api/random/fakta', upstream: '/random/fakta', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Kata Motivasi', desc: 'Kata motivasi dan inspirasi harian.', path: '/api/random/kata-motivasi', upstream: '/random/kata-motivasi', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Kucing', desc: 'Gambar kucing.', path: '/api/random/kucing', upstream: '/random/kucing', params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Nasehat', desc: 'Nasehat bijak.', path: '/api/random/nasehat', upstream: '/random/nasehat', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Neko', desc: 'Gambar neko acak.', path: '/api/random/neko', upstream: '/random/neko', params: [] },
  { server: 'dongtube', category: 'Random', name: 'Quote Filsuf', desc: 'Kutipan filsuf acak.', path: '/api/random/philosopher-quotes', upstream: '/random/philosopher-quotes', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Puisi', desc: 'Puisi.', path: '/api/random/puisi', upstream: '/random/puisi', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Random Quotes', desc: 'Quote acak.', path: '/api/random/quotes', upstream: '/random/quotes', keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Quote Tokoh', desc: 'Kutipan bijak tokoh dunia & filsuf.', path: '/api/random/tokoh-quotes', upstream: '/random/tokoh-quotes', params: [{ name: 'type', required: false, placeholder: 'Sumber kutipan', options: ['tokoh', 'filsuf'] }, { name: 'count', required: false, placeholder: '1' }] },
  { server: 'dongtube', category: 'Random', name: 'Random Waifu', desc: 'Gambar waifu anime acak (aman).', path: '/api/random/waifu', upstream: '/random/waifu', params: [{ name: 'count', required: false, placeholder: '5' }] },

  // ---------------------------------------------------------------- Search
  { server: 'dongtube', category: 'Search', name: 'AN1 APK Search', desc: 'Cari APK di AN1.com.', path: '/api/apk/an1', upstream: '/apk/an1', params: [{ name: 'q', required: true, placeholder: 'minecraft' }], sample: { q: 'minecraft' } },
  { server: 'dongtube', category: 'Search', name: 'APKMODY Search', desc: 'Cari aplikasi/game mod di APKMODY.', path: '/api/apk/apkmody', upstream: '/apk/apkmody', params: [{ name: 'q', required: true, placeholder: 'Nama aplikasi/game' }, { name: 'limit', required: false, placeholder: 'Jumlah hasil (maks 20)' }], sample: { q: 'minecraft' } },
  { server: 'dongtube', category: 'Search', name: 'Play Store Search', desc: 'Cari aplikasi di Google Play Store.', path: '/api/apk/playstore', upstream: '/apk/playstore', params: [{ name: 'q', required: true, placeholder: 'Nama aplikasi' }, { name: 'limit', required: false, placeholder: 'Jumlah hasil (maks 20)' }], sample: { q: 'whatsapp' } },
  { server: 'dongtube', category: 'Search', name: 'Douyin Trending', desc: 'Topik & video yang lagi trending di Douyin.', path: '/api/douyin/hot', upstream: '/douyin/hot', params: [] },
  { server: 'dongtube', category: 'Search', name: 'Pixiv Detail', desc: 'Detail artwork Pixiv (gambar, tag, penulis).', path: '/api/pixiv/detail', upstream: '/pixiv/detail', params: [{ name: 'id', required: true, placeholder: '123456789' }], sample: { id: '123456789' } },
  { server: 'dongtube', category: 'Search', name: 'APKPure Search', desc: 'Cari aplikasi & game di APKPure.', path: '/api/search/apkpure', upstream: '/search/apkpure', params: [{ name: 'q', required: true, placeholder: 'whatsapp' }, { name: 'limit', required: false, placeholder: '10' }], sample: { q: 'whatsapp' } },
  { server: 'dongtube', category: 'Search', name: 'Web Search (Bing)', desc: 'Cari apa aja di web, hasilnya cepat.', path: '/api/search/brave', upstream: '/search/brave', params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }, { name: 'count', required: false, placeholder: 'Jumlah hasil (maks 20)' }], sample: { q: 'indonesia' } },
  { server: 'dongtube', category: 'Search', name: 'Cookpad Resep', desc: 'Cari resep masakan di Cookpad Indonesia.', path: '/api/search/cookpad', upstream: '/search/cookpad', params: [{ name: 'q', required: true, placeholder: 'ayam kecap' }], sample: { q: 'ayam kecap' } },
  { server: 'dongtube', category: 'Search', name: 'DeviantArt Search', desc: 'Cari artwork di DeviantArt.', path: '/api/search/deviantart', upstream: '/search/deviantart', params: [{ name: 'q', required: true, placeholder: 'Kata kunci artwork' }, { name: 'limit', required: false, placeholder: 'Jumlah hasil (maks 60)' }], sample: { q: 'landscape' } },
  { server: 'dongtube', category: 'Search', name: 'DuckDuckGo Search', desc: 'Mesin pencari web DuckDuckGo.', path: '/api/search/duckduckgo', upstream: '/search/duckduckgo', keyOptional: true, params: [{ name: 'q', required: true, placeholder: 'indonesia' }], sample: { q: 'indonesia' } },
  { server: 'dongtube', category: 'Search', name: 'GitHub Repo Search', desc: 'Cari repository di GitHub.', path: '/api/search/github', upstream: '/search/github', params: [{ name: 'q', required: true, placeholder: 'whatsapp bot' }, { name: 'limit', required: false, placeholder: '10' }], sample: { q: 'whatsapp bot' } },
  { server: 'dongtube', category: 'Search', name: 'GSMArena Search', desc: 'Cari info HP di GSMArena.', path: '/api/search/gsmarena', upstream: '/search/gsmarena', params: [{ name: 'q', required: true, placeholder: 'Nama HP (e.g. samsung galaxy s24)' }], sample: { q: 'samsung galaxy s24' } },
  { server: 'dongtube', category: 'Search', name: 'Image Search', desc: 'Cari gambar di internet (safe search nyala).', path: '/api/search/image', upstream: '/search/image', fixed: { safe: '1' }, params: [{ name: 'q', required: true, placeholder: 'Kata kunci gambar' }, { name: 'limit', required: false, placeholder: '10' }, { name: 'size', required: false, placeholder: 'Filter ukuran', options: ['small', 'medium', 'large', 'wallpaper'] }], sample: { q: 'kucing' } },
  { server: 'dongtube', category: 'Search', name: 'iQIYI Search', desc: 'Cari drama, anime, dan film di iQIYI.', path: '/api/search/iqiyi', upstream: '/search/iqiyi', params: [{ name: 'q', required: true, placeholder: 'squid game' }], sample: { q: 'squid game' } },
  { server: 'dongtube', category: 'Search', name: 'KBBI', desc: 'Cari arti kata di KBBI (Bahasa Indonesia).', path: '/api/search/kbbi', upstream: '/search/kbbi', params: [{ name: 'q', required: true, placeholder: 'makan' }], sample: { q: 'makan' } },
  { server: 'dongtube', category: 'Search', name: 'MCPEDL Search', desc: 'Cari map/addon/skin Minecraft PE (MCPEDL) + link unduh.', path: '/api/search/mcpedl', upstream: '/search/mcpedl', params: [{ name: 'q', required: true, placeholder: 'skyblock' }, { name: 'page', required: false, placeholder: '1' }, { name: 'detail', required: false, placeholder: 'Ambil detail by slug?', options: ['false', 'true'] }], sample: { q: 'skyblock' } },
  { server: 'dongtube', category: 'Search', name: 'Movie Search (Cinesubz)', desc: 'Cari film di Cinesubz.', path: '/api/search/movie', upstream: '/search/movie', params: [{ name: 'q', required: true, placeholder: 'Judul film' }], sample: { q: 'avengers' } },
  { server: 'dongtube', category: 'Search', name: 'MyAnimeList Search', desc: 'Cari anime di MyAnimeList.', path: '/api/search/myanimelist', upstream: '/search/myanimelist', params: [{ name: 'q', required: true, placeholder: 'Judul anime' }], sample: { q: 'naruto' } },
  { server: 'dongtube', category: 'Search', name: 'Myinstants Search', desc: 'Cari sound button & soundboard Myinstants.', path: '/api/search/myinstant', upstream: '/search/myinstant', params: [{ name: 'q', required: true, placeholder: 'Nama suara' }, { name: 'limit', required: false, placeholder: 'Jumlah hasil (maks 30)' }], sample: { q: 'bruh' } },
  { server: 'dongtube', category: 'Search', name: 'Pexels Search', desc: 'Cari foto/video gratis di Pexels.', path: '/api/search/pexels', upstream: '/search/pexels', params: [{ name: 'q', required: true, placeholder: 'Kata kunci' }, { name: 'type', required: false, placeholder: 'Tipe media', options: ['photos', 'videos'] }], sample: { q: 'mountain' } },
  { server: 'dongtube', category: 'Search', name: 'PineDrama Search', desc: 'Cari drama Korea/China/Asia (PineDrama).', path: '/api/search/pinedrama', upstream: '/search/pinedrama', params: [{ name: 'q', required: true, placeholder: 'goblin' }], sample: { q: 'goblin' } },
  { server: 'dongtube', category: 'Search', name: 'Pixiv Search', desc: 'Cari artwork/ilustrasi di Pixiv (konten aman aja).', path: '/api/search/pixiv', upstream: '/search/pixiv', fixed: { mode: 'safe' }, params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }, { name: 'page', required: false, placeholder: 'Halaman' }, { name: 'order', required: false, placeholder: 'Urutan', options: ['date_d', 'date'] }], sample: { q: 'landscape' } },
  { server: 'dongtube', category: 'Search', name: 'SoundCloud Search', desc: 'Search lagu di SoundCloud.', path: '/api/search/soundcloud', upstream: '/search/soundcloud', params: [{ name: 'q', required: true, placeholder: 'Judul lagu/artis' }, { name: 'limit', required: false, placeholder: 'Jumlah hasil (maks 20)' }], sample: { q: 'lofi' } },
  { server: 'dongtube', category: 'Search', name: 'Spotify Search', desc: 'Cari lagu di Spotify.', path: '/api/search/spotify', upstream: '/search/spotify', params: [{ name: 'q', required: true, placeholder: 'dangdut' }], sample: { q: 'dangdut' } },
  { server: 'dongtube', category: 'Search', name: 'Wallpaper & Photo Search', desc: 'Cari wallpaper & foto gratis.', path: '/api/search/unsplash', upstream: '/search/unsplash', params: [{ name: 'q', required: true, placeholder: 'nature wallpaper' }, { name: 'count', required: false, placeholder: '10' }, { name: 'orientation', required: false, placeholder: 'Orientasi gambar', options: ['landscape', 'portrait', 'squarish'] }], sample: { q: 'nature wallpaper' } },
  { server: 'dongtube', category: 'Search', name: 'Wikipedia Search', desc: 'Cari artikel Wikipedia.', path: '/api/search/wikipedia', upstream: '/search/wikipedia', params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }], sample: { q: 'indonesia' } },
  { server: 'dongtube', category: 'Search', name: 'Top Anime MyAnimeList', desc: 'Top anime dari MyAnimeList (peringkat global).', path: '/api/top/myanimelist', upstream: '/top/myanimelist', params: [] },
  { server: 'dongtube', category: 'Search', name: 'MCPEDL Detail', desc: 'Detail addon MCPEDL plus link download-nya.', path: '/api/detail/mcpedl', upstream: '/detail/mcpedl', params: [{ name: 'slug', required: true, placeholder: 'Slug URL MCPEDL' }] },

  // ---------------------------------------------------------------- Stalk
  { server: 'dongtube', category: 'Stalk', name: 'Facebook Stalk', desc: 'Info halaman Facebook publik: nama & jumlah followers.', path: '/api/stalk/facebook', upstream: '/stalk/facebook', params: [{ name: 'username', required: true, placeholder: 'Username / nama halaman FB' }], sample: { username: 'facebook' } },
  { server: 'dongtube', category: 'Stalk', name: 'Genshin Stalk', desc: 'Stalk profil Genshin Impact (UID).', path: '/api/stalk/genshin', upstream: '/stalk/genshin', params: [{ name: 'uid', required: true, placeholder: '700000001' }], sample: { uid: '700000001' } },
  { server: 'dongtube', category: 'Stalk', name: 'Roblox Stalk', desc: 'Stalk profil Roblox.', path: '/api/stalk/roblox', upstream: '/stalk/roblox', params: [{ name: 'user', required: true, placeholder: 'Username Roblox' }], sample: { user: 'builderman' } },
  { server: 'dongtube', category: 'Stalk', name: 'TikTok Posts', desc: 'Daftar video yang diposting akun TikTok.', path: '/api/stalk/tiktok-posts', upstream: '/stalk/tiktok-posts', params: [{ name: 'user', required: true, placeholder: 'Username TikTok (tanpa @)' }], sample: { user: 'mrbeast' } },
  { server: 'dongtube', category: 'Stalk', name: 'X (Twitter) Stalk', desc: 'Info profil X (Twitter): nama, bio, followers, avatar.', path: '/api/stalk/twitter', upstream: '/stalk/twitter', params: [{ name: 'username', required: true, placeholder: 'Username tanpa @' }], sample: { username: 'elonmusk' } },
  { server: 'dongtube', category: 'Stalk', name: 'YouTube Stalk', desc: 'Info channel YouTube: subscriber, jumlah video, video terbaru.', path: '/api/stalk/youtube', upstream: '/stalk/youtube', params: [{ name: 'username', required: true, placeholder: 'Handle/username channel (@MrBeast atau MrBeast)' }], sample: { username: 'MrBeast' } },

  // ---------------------------------------------------------------- Tools
  { server: 'dongtube', category: 'Tools', name: 'TikTok Comments', desc: 'Ambil semua komentar video TikTok, plus balasannya.', path: '/api/comments/tiktok', upstream: '/comments/tiktok', params: [{ name: 'url', required: true, placeholder: 'URL video TikTok (vt.tiktok.com pun boleh) atau aweme_id' }, { name: 'replies', required: false, placeholder: 'Ambil balasan juga (1) atau hanya komentar utama (0)', options: ['1', '0'] }, { name: 'limit', required: false, placeholder: 'Batas komentar utama yang diambil (default tanpa batas, maks 10000)' }], sample: { url: 'https://vt.tiktok.com/ZSbpMHCBM/', limit: '5' } },
  { server: 'dongtube', category: 'Tools', name: 'Base64 to Text', desc: 'Konversi base64 ke teks.', path: '/api/tools/base642text', upstream: '/tools/base642text', keyOptional: true, params: [{ name: 'base64', required: true, placeholder: 'aGVsbG8=' }], sample: { base64: 'aGVsbG8=' } },
  { server: 'dongtube', category: 'Tools', name: 'Binary to Text', desc: 'Konversi binary ke teks.', path: '/api/tools/binary2text', upstream: '/tools/binary2text', keyOptional: true, params: [{ name: 'binary', required: true, placeholder: '01101000 01100101' }], sample: { binary: '01101000 01100101' } },
  { server: 'dongtube', category: 'Tools', name: 'Compare Phone', desc: 'Bandingkan spesifikasi dua HP berdampingan.', path: '/api/tools/compare-phone', upstream: '/tools/compare-phone', params: [{ name: 'phone1', required: true, placeholder: 'iphone 15 pro max' }, { name: 'phone2', required: true, placeholder: 'galaxy s24 ultra' }], sample: { phone1: 'iphone 15 pro max', phone2: 'galaxy s24 ultra' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Compress', desc: 'Kecilin ukuran gambar JPEG/WebP.', path: '/api/tools/compress', upstream: '/tools/compress', fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'quality', required: false, placeholder: 'Quality JPEG', options: ['40', '60', '70', '80', '90', '95'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Image Convert', desc: 'Ubah format gambar (webp/jpeg/png/tiff).', path: '/api/tools/convert', upstream: '/tools/convert', fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'format', required: false, placeholder: 'Format keluaran', options: ['webp', 'jpeg', 'png', 'tiff'] }], sample: { url: IMG, format: 'webp' } },
  { server: 'dongtube', category: 'Tools', name: 'Country Info', desc: 'Info lengkap tentang suatu negara.', path: '/api/tools/countryinfo', upstream: '/tools/countryinfo', params: [{ name: 'name', required: true, placeholder: 'Nama negara' }], sample: { name: 'indonesia' } },
  { server: 'dongtube', category: 'Tools', name: 'Currency Converter', desc: 'Konversi mata uang.', path: '/api/tools/currency', upstream: '/tools/currency', keyOptional: true, params: [{ name: 'amount', required: false, placeholder: '1' }, { name: 'from', required: false, placeholder: 'Mata uang asal', options: ['USD', 'IDR', 'EUR', 'JPY', 'GBP', 'SGD', 'MYR', 'AUD', 'CNY', 'SAR'] }, { name: 'to', required: false, placeholder: 'Mata uang tujuan', options: ['IDR', 'USD', 'EUR', 'JPY', 'GBP', 'SGD', 'MYR', 'AUD', 'CNY', 'SAR'] }], sample: { amount: '1', from: 'USD', to: 'IDR' } },
  { server: 'dongtube', category: 'Tools', name: 'DNS Lookup', desc: 'Cek record DNS sebuah domain.', path: '/api/tools/dns', upstream: '/tools/dns', params: [{ name: 'domain', required: true, placeholder: 'Domain name' }, { name: 'type', required: false, placeholder: 'DNS record type', options: ['A', 'AAAA', 'CNAME', 'MX', 'NS', 'TXT', 'SOA', 'SRV', 'CAA'] }], sample: { domain: 'google.com' } },
  { server: 'dongtube', category: 'Tools', name: 'Photo Enhance', desc: 'Bikin foto lebih cerah, lebih hidup, dan lebih tajam.', path: '/api/tools/enhance', upstream: '/tools/enhance', fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar (URL lengkap http/https)' }, { name: 'brightness', required: false, placeholder: 'Kecerahan (0.5–2.0)' }, { name: 'saturation', required: false, placeholder: 'Saturasi (0.5–2.0)' }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Font Detector', desc: 'Cek font apa aja yang dipakai sebuah website.', path: '/api/tools/font-interceptor', upstream: '/tools/font-interceptor', params: [{ name: 'url', required: true, placeholder: 'URL website' }], sample: { url: 'https://example.com' } },
  { server: 'dongtube', category: 'Tools', name: 'GitHub Roast', desc: 'Roast profil GitHub pakai AI.', path: '/api/tools/github-roast', upstream: '/tools/github-roast', params: [{ name: 'user', required: true, placeholder: 'Username GitHub' }], sample: { user: 'torvalds' } },
  { server: 'dongtube', category: 'Tools', name: 'Grammar Checker', desc: 'Cek & benerin grammar bahasa Inggris.', path: '/api/tools/grammar-checker', upstream: '/tools/grammar-checker', params: [{ name: 'text', required: true, placeholder: 'Teks bahasa Inggris yang akan dicek' }], sample: { text: 'she go to school' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Crop', desc: 'Potong gambar.', path: '/api/tools/iloveimg-crop', upstream: '/tools/iloveimg-crop', fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'x', required: false, placeholder: 'X posisi crop' }, { name: 'y', required: false, placeholder: 'Y posisi crop' }, { name: 'width', required: false, placeholder: 'Lebar crop (px)' }, { name: 'height', required: false, placeholder: 'Tinggi crop (px)' }], sample: { url: IMG, x: '0', y: '0', width: '50', height: '50' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Rotate', desc: 'Putar gambar.', path: '/api/tools/iloveimg-rotate', upstream: '/tools/iloveimg-rotate', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'degrees', required: false, placeholder: 'Derajat rotasi', options: ['90', '180', '270'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Image to Prompt', desc: 'Ubah gambar jadi prompt AI (Midjourney, DALL-E, Stable Diffusion, Flux).', path: '/api/tools/image-to-prompt', upstream: '/tools/image-to-prompt', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'model', required: false, placeholder: 'Target model AI', options: ['general', 'midjourney', 'dalle', 'stable_diffusion', 'flux'] }, { name: 'language', required: false, placeholder: 'Bahasa output', options: ['en', 'id', 'ja', 'ko', 'zh'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Bahasa Jawa', desc: 'Terjemahin ke bahasa Jawa (ngoko/krama) atau ubah ke aksara Jawa.', path: '/api/tools/jawa', upstream: '/tools/jawa', params: [{ name: 'text', required: true, placeholder: 'Apa kabar' }, { name: 'mode', required: false, placeholder: 'Mode', options: ['translate', 'aksara'] }, { name: 'from', required: false, placeholder: 'Bahasa asal (translate)', options: ['indo', 'jawa'] }, { name: 'to', required: false, placeholder: 'Bahasa tujuan (translate)', options: ['krama-alus', 'krama-lugu', 'ngoko'] }, { name: 'direction', required: false, placeholder: 'Arah konversi aksara', options: ['toJavanese', 'toLatin'] }], sample: { text: 'Apa kabar' } },
  { server: 'dongtube', category: 'Tools', name: 'Kode Pos', desc: 'Cari kode pos Indonesia.', path: '/api/tools/kodepos', upstream: '/tools/kodepos', keyOptional: true, params: [{ name: 'kota', required: false, placeholder: 'Nama kota/wilayah' }], sample: { kota: 'bandung' } },
  { server: 'dongtube', category: 'Tools', name: 'Remove Background', desc: 'Hapus background gambar pakai AI.', path: '/api/tools/removebg', upstream: '/tools/removebg', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar yang background-nya mau dihapus' }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Image Resize', desc: 'Ubah ukuran gambar, rasionya tetap.', path: '/api/tools/resize', upstream: '/tools/resize', fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'width', required: false, placeholder: '512' }, { name: 'height', required: false, placeholder: '512' }], sample: { url: IMG, width: '64' } },
  { server: 'dongtube', category: 'Tools', name: 'Website Screenshot', desc: 'Screenshot halaman web (PNG).', path: '/api/tools/screenshot', upstream: '/tools/screenshot', params: [{ name: 'url', required: true, placeholder: 'URL halaman (https)' }, { name: 'width', required: false, placeholder: 'Lebar browser' }, { name: 'height', required: false, placeholder: 'Tinggi viewport' }, { name: 'device', required: false, placeholder: 'Perangkat emulasi', options: ['desktop', 'mobile'] }], sample: { url: 'https://example.com' } },
  { server: 'dongtube', category: 'Tools', name: 'Shortlink', desc: 'Pendekin link panjang.', path: '/api/tools/shortlink', upstream: '/tools/shortlink', params: [{ name: 'url', required: true, placeholder: 'URL yang dipendekkan' }], sample: { url: 'https://example.com' } },
  { server: 'dongtube', category: 'Tools', name: 'Skip Link', desc: 'Lewatin link shortener, langsung ke tujuannya.', path: '/api/tools/skiplink', upstream: '/tools/skiplink', params: [{ name: 'url', required: true, placeholder: 'URL sumber' }], sample: { url: 'https://example.com' } },
  { server: 'dongtube', category: 'Tools', name: 'Text to Base64', desc: 'Konversi teks ke base64.', path: '/api/tools/text2base64', upstream: '/tools/text2base64', keyOptional: true, params: [{ name: 'text', required: true, placeholder: 'hello world' }], sample: { text: 'hello world' } },
  { server: 'dongtube', category: 'Tools', name: 'Text to Binary', desc: 'Konversi teks ke binary.', path: '/api/tools/text2binary', upstream: '/tools/text2binary', keyOptional: true, params: [{ name: 'text', required: true, placeholder: 'hello' }], sample: { text: 'hello' } },
  { server: 'dongtube', category: 'Tools', name: 'Text to QR', desc: 'Bikin QR code dari teks atau link.', path: '/api/tools/text2qr', upstream: '/tools/text2qr', params: [{ name: 'text', required: true, placeholder: 'Text atau URL untuk QR code' }], sample: { text: 'https://apiz2z.web.id' } },
  { server: 'dongtube', category: 'Tools', name: 'Translate', desc: 'Terjemahin teks, bahasa asalnya dideteksi otomatis.', path: '/api/tools/translate', upstream: '/tools/translate', params: [{ name: 'text', required: true, placeholder: 'Teks yang diterjemahkan' }, { name: 'source', required: false, placeholder: 'Kode bahasa asal (auto = deteksi)' }, { name: 'target', required: false, placeholder: 'Kode bahasa tujuan' }], sample: { text: 'selamat pagi', target: 'en' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Upscale', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/tools/upscale', upstream: '/tools/upscale', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'factor', required: false, placeholder: 'Faktor pembesaran', options: ['2', '4'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Username Generator', desc: 'Bikin ide username/gamertag.', path: '/api/tools/username-gen', upstream: '/tools/username-gen', params: [{ name: 'keyword', required: true, placeholder: 'Kata kunci / nama' }, { name: 'mode', required: false, placeholder: 'Mode generator', options: ['instans', 'ai', 'mix'] }, { name: 'theme', required: false, placeholder: 'Tema (mode=ai)', options: ['action', 'adventure', 'fantasy', 'historical', 'horror', 'mythology', 'nature', 'sci-fi', 'strategy'] }, { name: 'word2', required: false, placeholder: 'Kata kedua (mode=mix)' }], sample: { keyword: 'yannz' } },
  { server: 'dongtube', category: 'Tools', name: 'AI Vision', desc: 'Analisis gambar pakai AI: deskripsi, baca teks, atau jadi prompt.', path: '/api/tools/vision', upstream: '/tools/vision', keyOptional: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'mode', required: false, placeholder: 'Mode analisis', options: ['describe', 'prompt', 'ocr', 'all'] }, { name: 'lang', required: false, placeholder: 'Bahasa output', options: ['en', 'id', 'ja', 'ko', 'zh'] }, { name: 'question', required: false, placeholder: 'What objects are in this image?' }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'TikTok Hashtag Analyzer', desc: 'Analisis hashtag TikTok: top 10, yang terkait, dan yang lagi trending.', path: '/api/analyze/tiktok-hashtag', upstream: '/analyze/tiktok-hashtag', params: [{ name: 'tag', required: true, placeholder: 'anime' }], sample: { tag: 'anime' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · AI
  { server: 'dongtube', category: 'AI', name: 'AI Translate (Dongtube)', desc: 'Terjemahin teks ke banyak bahasa pakai AI.', path: '/api/dongtube/ai/cf-translate', upstream: '/ai/cf-translate', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Teks sumber' }, { name: 'to', required: false, placeholder: 'Bahasa tujuan (kode)', options: ['id', 'en', 'ja', 'ko', 'ar', 'zh-CN', 'es', 'fr', 'de', 'hi', 'ru', 'pt', 'it', 'th', 'vi', 'ms', 'tr', 'nl'] }, { name: 'from', required: false, placeholder: 'Bahasa asal (kosong = auto)' }], sample: { text: 'selamat pagi', to: 'en' } },
  { server: 'dongtube', category: 'AI', name: 'ChatGPT (Dongtube)', desc: 'Ngobrol sama ChatGPT.', path: '/api/dongtube/ai/chatgpt', upstream: '/ai/chatgpt', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'hi' }, { name: 'system', required: false, placeholder: 'System prompt (opsional)' }], sample: { q: 'Halo' } },
  { server: 'dongtube', category: 'AI', name: 'Claude AI (Dongtube)', desc: 'Ngobrol sama Claude AI.', path: '/api/dongtube/ai/claude', upstream: '/ai/claude', backupOnly: true, keyOptional: true, params: [{ name: 'q', required: true, placeholder: 'Pertanyaan' }], sample: { q: 'Halo' } },
  { server: 'dongtube', category: 'AI', name: 'Copilot AI (Dongtube)', desc: 'Ngobrol sama AI gaya Copilot. Buat bikin gambar pakai Pollinations Image.', path: '/api/dongtube/ai/copilot', upstream: '/ai/copilot', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Pertanyaan' }, { name: 'mode', required: false, placeholder: 'Mode (image dialihkan ke /ai/pollinations)', options: ['chat', 'image'] }], sample: { q: 'Halo' } },
  { server: 'dongtube', category: 'AI', name: 'Unlimited AI (Dongtube)', desc: 'Ngobrol sama AI gratis, ada 3 model.', path: '/api/dongtube/ai/unlimited', upstream: '/ai/unlimited', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Jelaskan tentang AI' }, { name: 'model', required: false, placeholder: 'Model AI', options: ['standard', 'reasoning', 'search'] }, { name: 'system', required: false, placeholder: 'Kamu adalah ahli SEO' }, { name: 'lang', required: false, placeholder: 'Bahasa respons', options: ['id', 'en', 'ja', 'ko', 'zh'] }], sample: { q: 'Halo' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Canvas
  { server: 'dongtube', category: 'Canvas', name: 'Brat (Dongtube)', desc: 'Gambar gaya \'brat\': teks gede, tema hitam/putih/hijau, bisa diblur.', path: '/api/dongtube/canvas/brat', upstream: '/canvas/brat', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo nama saya…' }, { name: 'theme', required: false, placeholder: 'Tema warna', options: ['white', 'black', 'green'] }, { name: 'blur', required: false, placeholder: 'Level blur teks', options: ['0', '1', '2', '3'] }], sample: { text: 'halo semua' } },
  { server: 'dongtube', category: 'Canvas', name: 'Brat Video (Dongtube)', desc: 'Video gaya \'brat\': katanya muncul satu-satu.', path: '/api/dongtube/canvas/bratvid', upstream: '/canvas/bratvid', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo Guys Nama Saya' }, { name: 'theme', required: false, placeholder: 'Tema warna', options: ['white', 'black', 'green'] }, { name: 'blur', required: false, placeholder: 'Blur teks', options: ['0', '1', '2', '3'] }, { name: 'format', required: false, placeholder: 'Format keluaran', options: ['mp4', 'gif'] }], sample: { text: 'halo semua' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Check
  { server: 'dongtube', category: 'Check', name: 'Cek Akun MLBB (Diamond) (Dongtube)', desc: 'Cek akun Mobile Legends & status first recharge diamond.', path: '/api/dongtube/check/mlbb-diamonds', upstream: '/check/mlbb-diamonds', backupOnly: true, params: [{ name: 'user_id', required: true, placeholder: 'User ID ML' }, { name: 'zone_id', required: true, placeholder: 'Zone ID ML' }], sample: { user_id: '1422073161', zone_id: '15910' } },
  { server: 'dongtube', category: 'Check', name: 'Cek Region MLBB (Dongtube)', desc: 'Cek nickname & region akun Mobile Legends.', path: '/api/dongtube/check/mlbb-region', upstream: '/check/mlbb-region', backupOnly: true, params: [{ name: 'user_id', required: true, placeholder: '1422073161' }, { name: 'zone_id', required: true, placeholder: '15910' }], sample: { user_id: '1422073161', zone_id: '15910' } },
  { server: 'dongtube', category: 'Check', name: 'NPM Search (Dongtube)', desc: 'Cari paket npm.', path: '/api/dongtube/check/npm', upstream: '/check/npm', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Nama package' }], sample: { q: 'express' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Downloader
  { server: 'dongtube', category: 'Downloader', name: 'AIO Downloader (Dongtube)', desc: 'Download dari banyak platform sekaligus, platformnya dideteksi otomatis.', path: '/api/dongtube/download/aio', upstream: '/download/aio', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL media dari platform apa pun yang didukung' }], sample: { url: 'https://vt.tiktok.com/ZSbpMHCBM/' } },
  { server: 'dongtube', category: 'Downloader', name: 'CapCut Downloader (Dongtube)', desc: 'Download template/video CapCut.', path: '/api/dongtube/download/capcut', upstream: '/download/capcut', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL CapCut' }] },
  { server: 'dongtube', category: 'Downloader', name: 'Facebook Downloader (Dongtube)', desc: 'Download video Facebook (reels/watch/post), mp4 HD/SD.', path: '/api/dongtube/download/facebook', upstream: '/download/facebook', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video Facebook' }] },
  { server: 'dongtube', category: 'Downloader', name: 'MediaFire Downloader (Dongtube)', desc: 'Download file dari MediaFire.', path: '/api/dongtube/download/mediafire', upstream: '/download/mediafire', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL file MediaFire' }] },
  { server: 'dongtube', category: 'Downloader', name: 'MediaFire Downloader v2 (Dongtube)', desc: 'Download file dari MediaFire.', path: '/api/dongtube/download/mediafire-v2', upstream: '/download/mediafire-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL MediaFire' }] },
  { server: 'dongtube', category: 'Downloader', name: 'Pinterest Downloader (Dongtube)', desc: 'Download gambar/video Pinterest kualitas terbaik.', path: '/api/dongtube/download/pinterest-v3', upstream: '/download/pinterest-v3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL pin Pinterest' }] },
  { server: 'dongtube', category: 'Downloader', name: 'SaveFrom Downloader (Dongtube)', desc: 'Download video dari banyak platform (YouTube, TikTok, dll).', path: '/api/dongtube/download/savefrom', upstream: '/download/savefrom', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video (YouTube, TikTok, dll)' }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes' } },
  { server: 'dongtube', category: 'Downloader', name: 'Spotify Downloader (Dongtube)', desc: 'Download lagu Spotify full MP3, bukan cuplikan.', path: '/api/dongtube/download/spotify-v2', upstream: '/download/spotify-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL track Spotify' }] },
  { server: 'dongtube', category: 'Downloader', name: 'Threads Downloader v2 (Dongtube)', desc: 'Download foto/video dari Threads.', path: '/api/dongtube/download/threads-v2', upstream: '/download/threads-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL post Threads' }] },
  { server: 'dongtube', category: 'Downloader', name: 'Threads Downloader v3 (Dongtube)', desc: 'Download foto/video dari Threads.', path: '/api/dongtube/download/threads-v3', upstream: '/download/threads-v3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL post Threads' }] },
  { server: 'dongtube', category: 'Downloader', name: 'TikTok Downloader (Dongtube)', desc: 'Download video TikTok tanpa watermark.', path: '/api/dongtube/download/tiktok', upstream: '/download/tiktok', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video TikTok' }], sample: { url: 'https://vt.tiktok.com/ZSbpMHCBM/' } },
  { server: 'dongtube', category: 'Downloader', name: 'X (Twitter) Downloader (Dongtube)', desc: 'Download media (foto/video) dari Twitter/X.', path: '/api/dongtube/download/twitter', upstream: '/download/twitter', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL tweet Twitter/X' }] },
  { server: 'dongtube', category: 'Downloader', name: 'X (Twitter) Downloader v2 (Dongtube)', desc: 'Download video/gambar dari X (Twitter), semua resolusi.', path: '/api/dongtube/download/twitter-v2', upstream: '/download/twitter-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL tweet/post Twitter/X' }] },
  { server: 'dongtube', category: 'Downloader', name: 'YouTube Downloader (Dongtube)', desc: 'Download video YouTube dalam berbagai kualitas.', path: '/api/dongtube/download/youtube', upstream: '/download/youtube', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video YouTube' }, { name: 'quality', required: false, placeholder: 'Kualitas video', options: ['144p', '240p', '360p', '480p', '720p', '1080p'] }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes', quality: '360p' } },
  { server: 'dongtube', category: 'Downloader', name: 'YouTube Downloader v2 (Dongtube)', desc: 'Download video YouTube, tinggal pilih kualitasnya.', path: '/api/dongtube/download/youtube-v2', upstream: '/download/youtube-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video YouTube' }, { name: 'quality', required: false, placeholder: 'Kualitas video', options: ['144p', '240p', '360p', '480p', '720p', '1080p'] }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes', quality: '360p' } },
  { server: 'dongtube', category: 'Downloader', name: 'YouTube Downloader v3 (Dongtube)', desc: 'Download YouTube jadi MP3 atau MP4.', path: '/api/dongtube/download/youtube-v3', upstream: '/download/youtube-v3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video YouTube' }, { name: 'type', required: false, placeholder: 'Jenis media', options: ['audio', 'video'] }, { name: 'quality', required: false, placeholder: 'Kualitas', options: ['128', '320', '360', '720', '1080'] }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes', type: 'audio', quality: '128' } },
  { server: 'dongtube', category: 'Downloader', name: 'YouTube MP3 (Dongtube)', desc: 'Download audio MP3 dari video YouTube.', path: '/api/dongtube/download/ytmp3', upstream: '/download/ytmp3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video YouTube' }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes' } },
  { server: 'dongtube', category: 'Downloader', name: 'YouTube MP3 v2 (Dongtube)', desc: 'Download audio MP3 dari video YouTube.', path: '/api/dongtube/download/ytmp3-v2', upstream: '/download/ytmp3-v2', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video YouTube' }, { name: 'quality', required: false, placeholder: 'Bitrate audio (kbps)', options: ['128', '256', '320'] }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes' } },
  { server: 'dongtube', category: 'Downloader', name: 'CNVMP3 (Dongtube)', desc: 'Ubah video YouTube jadi MP3/MP4.', path: '/api/dongtube/downloader/cnvmp3', upstream: '/downloader/cnvmp3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL video (YouTube, Shorts, dll)' }, { name: 'type', required: false, placeholder: 'mp3' }], sample: { url: 'https://youtube.com/shorts/5fs0aY9jYes', type: 'mp3' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Games
  { server: 'dongtube', category: 'Games', name: 'Susun Kata v2 (Dongtube)', desc: 'Kuis susun-kata.', path: '/api/dongtube/games/susun-kata', upstream: '/games/susun-kata', backupOnly: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Bendera (Dongtube)', desc: 'Kuis tebak-bendera.', path: '/api/dongtube/games/tebak-bendera', upstream: '/games/tebak-bendera', backupOnly: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Gambar (Dongtube)', desc: 'Kuis tebak-gambar.', path: '/api/dongtube/games/tebak-gambar', upstream: '/games/tebak-gambar', backupOnly: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Game (Dongtube)', desc: 'Kuis tebak-game.', path: '/api/dongtube/games/tebak-game', upstream: '/games/tebak-game', backupOnly: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Hero ML (Dongtube)', desc: 'Kuis tebak-heroml.', path: '/api/dongtube/games/tebak-heroml', upstream: '/games/tebak-heroml', backupOnly: true, params: [] },
  { server: 'dongtube', category: 'Games', name: 'Tebak Kata (Dongtube)', desc: 'Kuis tebak-kata.', path: '/api/dongtube/games/tebak-kata', upstream: '/games/tebak-kata', backupOnly: true, params: [] },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Image
  { server: 'dongtube', category: 'Image', name: 'iHancer (Dongtube)', desc: 'Perjelas kualitas gambar pakai AI.', path: '/api/dongtube/tools/ihancer', upstream: '/tools/ihancer', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar sumber' }, { name: 'method', required: false, placeholder: 'Metode enhance (1-4)' }, { name: 'size', required: false, placeholder: 'Ukuran maksimal', options: ['low', 'medium', 'high'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Image', name: 'TinyPNG Compress (Dongtube)', desc: 'Kecilin ukuran gambar JPG/PNG/WebP.', path: '/api/dongtube/imgedit/tinypng', upstream: '/imgedit/tinypng', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar yang dikompres' }, { name: 'rehost', required: false, placeholder: 'Rehost hasil?', options: ['true', 'false'] }], sample: { url: IMG } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Maker
  { server: 'dongtube', category: 'Maker', name: 'Brat v2 (Dongtube)', desc: 'Gambar teks gaya brat.', path: '/api/dongtube/maker/brat', upstream: '/maker/brat', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'hello world' }, { name: 'theme', required: false, placeholder: 'Tema warna', options: ['green', 'white', 'black'] }], sample: { text: 'halo semua' } },
  { server: 'dongtube', category: 'Maker', name: 'iPhone Quote Chat v2 (Dongtube)', desc: 'Gambar bubble chat iPhone.', path: '/api/dongtube/maker/iqc', upstream: '/maker/iqc', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo bro apa kabar?' }], sample: { text: 'halo' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Music
  { server: 'dongtube', category: 'Music', name: 'Spotify Play (Dongtube)', desc: 'Cari lagu Spotify langsung dapet MP3 full.', path: '/api/dongtube/spotify/play', upstream: '/spotify/play', backupOnly: true, params: [{ name: 'input', required: true, placeholder: 'Nama lagu/artis ATAU URL Spotify' }], sample: { input: 'coldplay yellow' } },
  { server: 'dongtube', category: 'Music', name: 'YouTube Play (Dongtube)', desc: 'Cari lagu YouTube (judul atau link) langsung dapet MP3 full.', path: '/api/dongtube/youtube/play', upstream: '/youtube/play', backupOnly: true, params: [{ name: 'input', required: true, placeholder: 'Nama lagu ATAU URL YouTube' }], sample: { input: 'coldplay yellow' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Primbon
  { server: 'dongtube', category: 'Primbon', name: 'Kecocokan Pasangan v2 (Dongtube)', desc: 'Ramalan kecocokan cinta berdasarkan nama pasangan (Primbon).', path: '/api/dongtube/primbon/cocok-pasangan', upstream: '/primbon/cocok-pasangan', backupOnly: true, params: [{ name: 'nama1', required: true, placeholder: 'Nama Anda' }, { name: 'nama2', required: true, placeholder: 'siti' }], sample: { nama1: 'budi', nama2: 'siti' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Random
  { server: 'dongtube', category: 'Random', name: 'Anime Quote v2 (Dongtube)', desc: 'Quote anime acak.', path: '/api/dongtube/random/anime-quotes', upstream: '/random/anime-quotes', backupOnly: true, keyOptional: true, params: [] },
  { server: 'dongtube', category: 'Random', name: 'Anime Quote v3 (Dongtube)', desc: 'Quote anime acak.', path: '/api/dongtube/random/quotesanime', upstream: '/random/quotesanime', backupOnly: true, params: [] },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Search
  { server: 'dongtube', category: 'Search', name: 'Google Image Search (Dongtube)', desc: 'Cari gambar di internet.', path: '/api/dongtube/search/googleimg', upstream: '/search/googleimg', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'pemandangan' }, { name: 'count', required: false, placeholder: 'Jumlah hasil (maks 30)' }], sample: { q: 'pemandangan' } },
  { server: 'dongtube', category: 'Search', name: 'Lyrics Search (Dongtube)', desc: 'Cari lirik lagu, ada versi yang nyambung sama waktunya juga.', path: '/api/dongtube/search/lyrics', upstream: '/search/lyrics', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'never gonna give you up' }, { name: 'track', required: false, placeholder: 'Nama track (pencarian presisi)' }, { name: 'artist', required: false, placeholder: 'Nama artis (pencarian presisi)' }], sample: { q: 'never gonna give you up' } },
  { server: 'dongtube', category: 'Search', name: 'Musixmatch Lyrics (Dongtube)', desc: 'Cari lirik lagu.', path: '/api/dongtube/search/musixmatch', upstream: '/search/musixmatch', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Judul lagu / artis' }, { name: 'with_lyrics', required: false, placeholder: 'Sertakan teks lirik', options: ['true', 'false'] }], sample: { q: 'yellow coldplay' } },
  { server: 'dongtube', category: 'Search', name: 'Pinterest Search (Dongtube)', desc: 'Cari pin Pinterest lengkap sama gambarnya.', path: '/api/dongtube/search/pinterest', upstream: '/search/pinterest', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }, { name: 'count', required: false, placeholder: 'Jumlah hasil (maks 50)' }], sample: { q: 'aesthetic wallpaper' } },
  { server: 'dongtube', category: 'Search', name: 'Pinterest Search v2 (Dongtube)', desc: 'Cari pin Pinterest lengkap sama gambarnya.', path: '/api/dongtube/search/pinterest-v2', upstream: '/search/pinterest-v2', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }, { name: 'count', required: false, placeholder: 'Jumlah hasil (maks 50)' }], sample: { q: 'aesthetic wallpaper' } },
  { server: 'dongtube', category: 'Search', name: 'Sticker Search (Dongtube)', desc: 'Cari sticker pack WhatsApp.', path: '/api/dongtube/search/sticker', upstream: '/search/sticker', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'anime' }], sample: { q: 'anime' } },
  { server: 'dongtube', category: 'Search', name: 'Sticker.ly Search (Dongtube)', desc: 'Cari sticker pack di Sticker.ly (WhatsApp).', path: '/api/dongtube/search/stickerly', upstream: '/search/stickerly', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Kata kunci sticker' }], sample: { q: 'anime' } },
  { server: 'dongtube', category: 'Search', name: 'YouTube Search (Dongtube)', desc: 'Cari video YouTube.', path: '/api/dongtube/search/youtube', upstream: '/search/youtube', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Kata kunci pencarian' }], sample: { q: 'lofi hip hop' } },
  { server: 'dongtube', category: 'Search', name: 'TikTok Search (Dongtube)', desc: 'Cari video TikTok.', path: '/api/dongtube/tiktok/search', upstream: '/tiktok/search', backupOnly: true, params: [{ name: 'keyword', required: true, placeholder: 'cat' }, { name: 'count', required: false, placeholder: '10' }], sample: { keyword: 'kucing lucu' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Stalk
  { server: 'dongtube', category: 'Stalk', name: 'GitHub Stalk (Dongtube)', desc: 'Stalk profil GitHub.', path: '/api/dongtube/stalk/github', upstream: '/stalk/github', backupOnly: true, params: [{ name: 'user', required: true, placeholder: 'Username GitHub' }], sample: { user: 'torvalds' } },
  { server: 'dongtube', category: 'Stalk', name: 'Instagram Stalk (Dongtube)', desc: 'Info profil Instagram publik.', path: '/api/dongtube/stalk/instagram-v2', upstream: '/stalk/instagram-v2', backupOnly: true, params: [{ name: 'user', required: true, placeholder: 'instagram' }], sample: { user: 'instagram' } },
  { server: 'dongtube', category: 'Stalk', name: 'TikTok Stalk (Dongtube)', desc: 'Stalk profil TikTok.', path: '/api/dongtube/stalk/tiktok', upstream: '/stalk/tiktok', backupOnly: true, params: [{ name: 'user', required: true, placeholder: 'mrbeast' }], sample: { user: 'mrbeast' } },
  { server: 'dongtube', category: 'Stalk', name: 'TikTok Stalk v2 (Dongtube)', desc: 'Info profil TikTok plus analitik (engagement, perkiraan penghasilan).', path: '/api/dongtube/stalk/tiktok-v2', upstream: '/stalk/tiktok-v2', backupOnly: true, params: [{ name: 'user', required: true, placeholder: 'Username TikTok' }], sample: { user: 'mrbeast' } },
  { server: 'dongtube', category: 'Stalk', name: 'TikTok Stalk v3 (Dongtube)', desc: 'Info profil TikTok lengkap plus analitik dan potensi berkembang.', path: '/api/dongtube/stalk/tiktok-v3', upstream: '/stalk/tiktok-v3', backupOnly: true, params: [{ name: 'user', required: true, placeholder: 'Username TikTok' }], sample: { user: 'mrbeast' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly) · Tools
  { server: 'dongtube', category: 'Tools', name: 'Edge TTS (Dongtube)', desc: 'Ubah teks jadi suara natural (Microsoft Edge).', path: '/api/dongtube/tools/edge-tts', upstream: '/tools/edge-tts', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'halo dunia' }, { name: 'voice', required: false, placeholder: 'Suara', options: ['id-ID-ArdiNeural', 'id-ID-GadisNeural', 'en-US-AriaNeural', 'en-US-GuyNeural', 'ja-JP-NanamiNeural', 'ko-KR-SunHiNeural'] }], sample: { text: 'halo dunia' } },
  { server: 'dongtube', category: 'Tools', name: 'Google TTS (Dongtube)', desc: 'Ubah teks jadi suara Google Translate (MP3).', path: '/api/dongtube/tools/google-tts', upstream: '/tools/google-tts', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'halo dunia' }, { name: 'lang', required: false, placeholder: 'Kode bahasa (id, en, ja…)', options: ['id', 'en', 'ja', 'ko', 'ar', 'es', 'fr', 'de', 'ru', 'zh-CN'] }, { name: 'slow', required: false, placeholder: 'Pelan untuk belajar', options: ['false', 'true'] }], sample: { text: 'halo dunia' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Compress (iLoveIMG) (Dongtube)', desc: 'Kecilin ukuran gambar.', path: '/api/dongtube/tools/iloveimg-compress', upstream: '/tools/iloveimg-compress', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'level', required: false, placeholder: 'Level kompresi (1=low, 4=maximum)', options: ['1', '2', '3', '4'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Remove Background (iLoveIMG) (Dongtube)', desc: 'Hapus background gambar.', path: '/api/dongtube/tools/iloveimg-removebg', upstream: '/tools/iloveimg-removebg', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Image Resize (iLoveIMG) (Dongtube)', desc: 'Ubah ukuran gambar.', path: '/api/dongtube/tools/iloveimg-resize', upstream: '/tools/iloveimg-resize', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: false }, params: [{ name: 'url', required: false, placeholder: 'URL gambar' }, { name: 'width', required: false, placeholder: 'Lebar target (px)' }, { name: 'height', required: false, placeholder: 'Tinggi target (px)' }, { name: 'percent', required: false, placeholder: 'Persentase resize (25/50/75)' }, { name: 'filename', required: false, placeholder: 'Nama file output' }], sample: { url: IMG, percent: '50' } },
  { server: 'dongtube', category: 'Tools', name: 'Image Upscale (iLoveIMG) (Dongtube)', desc: 'Perbesar resolusi gambar.', path: '/api/dongtube/tools/iloveimg-upscale', upstream: '/tools/iloveimg-upscale', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'scale', required: false, placeholder: 'Skala upscale', options: ['2', '4'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'KBBI v2 (Dongtube)', desc: 'Cari arti kata di KBBI.', path: '/api/dongtube/tools/kbbi', upstream: '/tools/kbbi', backupOnly: true, params: [{ name: 'word', required: true, placeholder: 'Kata yang ingin dicari' }], sample: { word: 'makan' } },
  { server: 'dongtube', category: 'Tools', name: 'Remini v2 (Dongtube)', desc: 'Perjelas & perbesar gambar 2x pakai AI.', path: '/api/dongtube/tools/remini', upstream: '/tools/remini', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar yang akan di-upscale' }, { name: 'method', required: false, placeholder: 'Metode enhance (1 = 2x upscale)', options: ['1', '2', '3', '4'] }], sample: { url: IMG } },
  { server: 'dongtube', category: 'Tools', name: 'Website Screenshot v2 (Dongtube)', desc: 'Screenshot website versi desktop atau HP.', path: '/api/dongtube/tools/ssweb', upstream: '/tools/ssweb', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'URL situs yang di-screenshot' }, { name: 'mode', required: false, placeholder: 'Mode perangkat', options: ['desktop', 'mobile'] }, { name: 'full', required: false, placeholder: 'Full page?', options: ['false', 'true'] }], sample: { url: 'https://example.com' } },
  { server: 'dongtube', category: 'Tools', name: 'Translate v2 (Dongtube)', desc: 'Terjemahin teks.', path: '/api/dongtube/tools/translate-v2', upstream: '/tools/translate-v2', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Teks yang akan diterjemahkan' }, { name: 'from', required: false, placeholder: 'Bahasa asal (auto)' }, { name: 'to', required: false, placeholder: 'Bahasa tujuan' }], sample: { text: 'selamat pagi', to: 'en' } },
  { server: 'dongtube', category: 'Tools', name: 'Text to Speech v2 (Dongtube)', desc: 'Ubah teks jadi suara.', path: '/api/dongtube/tools/tts', upstream: '/tools/tts', backupOnly: true, keyOptional: true, params: [{ name: 'text', required: true, placeholder: 'selamat pagi' }, { name: 'lang', required: false, placeholder: 'Bahasa suara', options: ['id', 'en', 'ja', 'ko', 'ar', 'zh-CN', 'es', 'fr', 'de', 'hi', 'ru', 'pt', 'it', 'th', 'vi', 'ms', 'tr', 'nl'] }], sample: { text: 'selamat pagi' } },
];

module.exports = SPECS.map(makeEndpoint);
