'use strict';
// Endpoints from NexRay (https://api.nexray.eu.cc), proxied through lib/apiproxy.js. The server is
// public (no key); it only ever runs in the background: its name and links never reach the caller.
//
// Generated from its docs (/category/*) after trying every endpoint against the live API, with
// these rules:
//   - New on this site and working: listed as a new endpoint.
//   - Same as an endpoint the site already has, both working: listed as the next version
//     (e.g. /api/download/tiktok-v3) and added to that endpoint's backups.
//   - Same as an existing endpoint, one of the two not working: the NexRay one is a backup only
//     (/api/alt3/...), so the site switches between them (config/endpointGroups.js).
//   - Both not working: same as above; the automatic check hides the endpoint while every member
//     of its group fails, and the Developer panel lists the errors.
// `rename` keeps the site's parameter names where NexRay calls them differently.
//
// Left out on purpose:
//   - /ai/bypass: bypass deteksi AI.
//   - /downloader/videy: situs video dewasa.
//   - /ephoto/hitam: ubah warna kulit (rasis).
//   - /information/cektagihanpln: data tagihan orang lain.
//   - /information/check-rekening: data pemilik rekening.
//   - /maker/fakebank-jago: bukti saldo palsu.
//   - /maker/fakedana: bukti saldo palsu.
//   - /maker/fakelobyff: akun/lobby palsu.
//   - /maker/fakelobyml: akun/lobby palsu.
//   - /maker/fakestory: story Instagram palsu orang lain.
//   - /maker/fakethreads: postingan Threads palsu orang lain.
//   - /payment/saweria/check: pembayaran akun orang lain.
//   - /payment/saweria/create: pembayaran akun orang lain.
//   - /random/cecan/china: foto orang asli acak.
//   - /random/cecan/indonesia: foto orang asli acak.
//   - /random/cecan/japan: foto orang asli acak.
//   - /random/cecan/korea: foto orang asli acak.
//   - /random/cecan/thailand: foto orang asli acak.
//   - /random/cecan/vietnam: foto orang asli acak.
//   - /random/loli: konten tidak pantas.
//   - /random/pap: konten tidak pantas.
//   - /textpro/pornhub: konten dewasa.
//   - /tools/faceswap: tukar wajah (deepfake).
//   - /tools/nikparse: data pribadi dari NIK.
//   - /tools/skip/adlinksumo: lewatin iklan shortlink.
//   - /tools/spamngl: spam pesan anonim.
//   - /tools/temp-nexray: email sementara buat daftar akun.
//   - /tools/v1/virtual-number: nomor OTP buat lewatin verifikasi.
//   - /tools/vcc: nomor kartu kredit.
//   - /tools/virtual-number: nomor OTP buat lewatin verifikasi.
// Not working when tried (left out; add again once they answer):
//   /ai/alisia, /ai/andisearch, /ai/deepimg, /ai/deepseek, /ai/dgaf
//   /ai/dolphin, /ai/dreamanalyze, /ai/duck, /ai/felo, /ai/glm
//   /ai/hammer, /ai/heck, /ai/islamcity, /ai/jadve, /ai/jeeves
//   /ai/llamacoder, /ai/nexray, /ai/nowtech, /ai/openai, /ai/perplexity
//   /ai/quillbot, /ai/riple, /ai/schoolhub, /ai/skole, /ai/suno
//   /ai/turbochat, /ai/v1/text2image, /ai/veo2, /ai/veo3, /ai/zahanat
//   /anime/anichin/genre, /anime/anichin/genres, /anime/anichin/home, /anime/anichin/schedule, /anime/anichin/stream
//   /anime/komiku/home, /anime/samehadaku/detail, /anime/samehadaku/embed, /anime/samehadaku/home, /anime/samehadaku/page
//   /anime/samehadaku/search, /anime/samehadaku/stream, /canvas/mpls, /downloader/cocofun, /downloader/krakenfiles
//   /downloader/mega, /downloader/smule, /downloader/webmusic, /downloader/ytplayvid, /editor/wanted
//   /ephoto/anime, /ephoto/art, /ephoto/borealis, /ephoto/botak, /ephoto/chibi
//   /ephoto/cinematic, /ephoto/comic, /ephoto/fairglow, /ephoto/ghibli, /ephoto/luminare
//   /ephoto/mafia, /ephoto/mirror, /ephoto/monochrome, /ephoto/mountain, /ephoto/nft
//   /ephoto/playlist, /ephoto/qin, /ephoto/real, /ephoto/statue, /ephoto/street
//   /ephoto/v1/figure, /ephoto/v2/figure, /maker/ustadz, /search/terabox, /search/tidal
//   /stalker/snackvideo, /tools/cekresi, /tools/colorize, /tools/hdvideo, /tools/html2img
//   /tools/image2qr, /tools/unblur, /tools/upscale, /tools/v1/hdvideo, /tools/wink
//   (POST endpoints that need an upload are not proxied.)
const { makeEndpoint } = require('../lib/apiproxy');
const { checkSampleImage } = require('../lib/theresav');
// Sample photo for the automatic endpoint check (the real request uses the caller's own image).
const IMG = checkSampleImage();

const SPECS = [
  // ---------------------------------------------------------------- AI
  { server: 'nexray', category: 'AI', name: 'Claude AI v2', desc: 'Chat with Claude Haiku 4.5 via Overchat API.', path: '/api/ai/claude-v2', upstream: '/ai/claude', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Copilot AI v2', desc: 'Chat with Microsoft Copilot AI, supports Web Search, Study Mode, Conversation, and Vision.', path: '/api/ai/copilot-v2', upstream: '/ai/copilot', rename: { prompt: 'text' }, params: [{ name: 'prompt', required: true, placeholder: 'Halo apa kabar...' }], sample: { prompt: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'DeepSearch', desc: 'Riset pakai AI: cari dari banyak sumber terus dirangkum.', path: '/api/ai/deepsearch', upstream: '/ai/deepsearch', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Dracin Tts', desc: 'Ubah teks jadi suara ala narator drama China.', path: '/api/ai/dracin-tts', upstream: '/ai/dracin-tts', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'speed', required: false, placeholder: '1.0' }, { name: 'volume', required: false, placeholder: '0.3' }, { name: 'music', required: false, placeholder: 'true' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Epsilon', desc: 'Cari jurnal/paper akademik pakai AI.', path: '/api/ai/epsilon', upstream: '/ai/epsilon', params: [{ name: 'text', required: true, placeholder: 'JAKARTA' }], sample: { text: 'JAKARTA' } },
  { server: 'nexray', category: 'AI', name: 'Flux v1', desc: 'Bikin gambar dari teks pakai AI Flux.', path: '/api/ai/flux', upstream: '/ai/v1/flux', params: [{ name: 'prompt', required: true, placeholder: 'Neon Samurai' }], sample: { prompt: 'Neon Samurai' } },
  { server: 'nexray', category: 'AI', name: 'Gemini Tts', desc: 'Ubah teks jadi suara pakai Gemini TTS.', path: '/api/ai/gemini-tts', upstream: '/ai/gemini-tts', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'GitaGPT', desc: 'Tanya jawab seputar Bhagavad Gita pakai AI.', path: '/api/ai/gitagpt', upstream: '/ai/gitagpt', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'GPT-3.5 Turbo', desc: 'Ngobrol sama GPT-3.5 Turbo.', path: '/api/ai/gpt-3.5-turbo', upstream: '/ai/gpt-3.5-turbo', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Ideogram', desc: 'Bikin gambar dari teks pakai AI Ideogram.', path: '/api/ai/ideogram', upstream: '/ai/ideogram', params: [{ name: 'prompt', required: true, placeholder: 'a beautiful sunset' }], sample: { prompt: 'a beautiful sunset' } },
  { server: 'nexray', category: 'AI', name: 'Islamic', desc: 'Tanya jawab seputar Islam pakai AI.', path: '/api/ai/islamic', upstream: '/ai/islamic', params: [{ name: 'text', required: true, placeholder: 'Apa itu Islam?' }], sample: { text: 'Apa itu Islam?' } },
  { server: 'nexray', category: 'AI', name: 'Kimi', desc: 'Ngobrol sama Kimi AI.', path: '/api/ai/kimi', upstream: '/ai/kimi', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Lumin', desc: 'Ngobrol sama Lumin AI.', path: '/api/ai/lumin', upstream: '/ai/lumin', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'MagicStudio', desc: 'Bikin gambar dari teks pakai MagicStudio.', path: '/api/ai/magicstudio', upstream: '/ai/magicstudio', params: [{ name: 'prompt', required: true, placeholder: 'a beautiful sunset over mountains' }], sample: { prompt: 'a beautiful sunset over mountains' } },
  { server: 'nexray', category: 'AI', name: 'MathGPT', desc: 'Bantu ngerjain soal matematika pakai AI.', path: '/api/ai/mathgpt', upstream: '/ai/mathgpt', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Monica', desc: 'Ngobrol sama Monica AI.', path: '/api/ai/monica', upstream: '/ai/monica', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Morphic', desc: 'Ngobrol sama Morphic AI, jawabannya pakai sumber dari web.', path: '/api/ai/morphic', upstream: '/ai/morphic', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Muslim AI v2', desc: 'Quran-based Q&A using MuslimAI with Dragonfly session support.', path: '/api/ai/muslimai-v2', upstream: '/ai/muslim', rename: { query: 'text' }, params: [{ name: 'query', required: true, placeholder: 'Apa itu Islam?' }], sample: { query: 'Apa itu Islam?' } },
  { server: 'nexray', category: 'AI', name: 'Natalie', desc: 'Ngobrol sama Natalie AI.', path: '/api/ai/natalie', upstream: '/ai/Natalie', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'NSFW Check v2', desc: 'Deteksi apakah sebuah gambar NSFW (unggah atau URL).', path: '/api/ai/nsfw-check-v2', upstream: '/tools/nsfw-checker', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'AI', name: 'Overchat', desc: 'Ngobrol sama Overchat AI.', path: '/api/ai/overchat', upstream: '/ai/overchat', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'PowerBrain v2', desc: 'Chat AI PowerBrain.', path: '/api/ai/powerbrain-v2', upstream: '/ai/powerbrain', rename: { prompt: 'text' }, params: [{ name: 'prompt', required: true, placeholder: 'Halo apa kabar...' }], sample: { prompt: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Public AI v2', desc: 'Chat with Public AI with Dragonfly session support.', path: '/api/ai/publicai-v2', upstream: '/ai/public', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Scren App', desc: 'Tanya AI soal isi gambar: kirim gambar plus pertanyaannya.', path: '/api/ai/screnapp', upstream: '/ai/screnapp', fileUrl: { param: 'url_image', accept: 'image/*', required: true }, params: [{ name: 'url_image', required: true, placeholder: 'URL gambar' }, { name: 'text', required: true, placeholder: 'Ini siapa...' }], sample: { url_image: IMG, text: 'Ini siapa' } },
  { server: 'nexray', category: 'AI', name: 'Simi Simi', desc: 'Ngobrol santai sama SimSimi.', path: '/api/ai/simisimi', upstream: '/ai/simisimi', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Sologo', desc: 'Bikin logo dari deskripsi pakai AI.', path: '/api/ai/sologo', upstream: '/ai/sologo', params: [{ name: 'prompt', required: true, placeholder: 'coffee shop logo' }], sample: { prompt: 'coffee shop logo' } },
  { server: 'nexray', category: 'AI', name: 'Story', desc: 'Bikin cerita dari ide kamu: pilih genre, panjang, dan tingkat kreatifnya.', path: '/api/ai/story', upstream: '/ai/story', params: [{ name: 'prompt', required: true, placeholder: 'A little boy and a cat' }, { name: 'mode', required: false, options: ['Any genre', 'Action', 'Sci-fi', 'Mystery', 'Biography', 'Young Adult', 'Crime', 'Horror', 'Thriller', 'Children Books', 'Non-fiction', 'Humor', 'Historical Fiction'] }, { name: 'length', required: false, options: ['Short', 'Novel'] }, { name: 'creative', required: false, options: ['Medium', 'High'] }], sample: { prompt: 'A little boy and a cat' } },
  { server: 'nexray', category: 'AI', name: 'Vider', desc: 'Bikin gambar dari teks pakai AI Vider.', path: '/api/ai/vider', upstream: '/ai/vider', params: [{ name: 'prompt', required: true, placeholder: 'A beautiful sunset over the ocean' }], sample: { prompt: 'A beautiful sunset over the ocean' } },
  { server: 'nexray', category: 'AI', name: 'WebPilot AI v2', desc: 'Web-searching AI assistant via Webpilot API with Dragonfly session support.', path: '/api/ai/webpilot-v2', upstream: '/ai/webpilot', params: [{ name: 'text', required: true, placeholder: 'berita terbaru yang ada di Indonesia' }], sample: { text: 'berita terbaru yang ada di Indonesia' } },
  { server: 'nexray', category: 'AI', name: 'Write Cream', desc: 'Ngobrol sama AI Writecream, bisa dikasih instruksi peran (logic).', path: '/api/ai/writecream', upstream: '/ai/writecream', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'logic', required: true, placeholder: 'Kamu adalah asisten yang baik' }], sample: { text: 'Halo apa kabar', logic: 'Kamu adalah asisten yang baik' } },
  { server: 'nexray', category: 'AI', name: 'Write Cream Image', desc: 'Bikin gambar dari teks dengan pilihan rasio.', path: '/api/ai/writecreamimg', upstream: '/ai/writecreamimg', params: [{ name: 'prompt', required: true, placeholder: 'girl wearing glasses' }, { name: 'ratio', required: false, options: ['1:1', '16:9', '2:3', '3:2', '4:5', '5:4', '9:16', '21:9', '9:21'] }], sample: { prompt: 'girl wearing glasses' } },

  // ---------------------------------------------------------------- Anime
  { server: 'nexray', category: 'Anime', name: 'Komiku Chapter', desc: 'Ambil semua gambar halaman dari satu chapter manga Komiku.', path: '/api/anime/komiku/chapter', upstream: '/anime/komiku/chapter', params: [{ name: 'url', required: true, placeholder: 'https://komiku.org/solo-leveling-ragnarok-chapter-68/' }], sample: { url: 'https://komiku.org/solo-leveling-ragnarok-chapter-68/' } },
  { server: 'nexray', category: 'Anime', name: 'Komiku Detail', desc: 'Detail manga Komiku: sinopsis, genre, dan daftar chapter.', path: '/api/anime/komiku/detail', upstream: '/anime/komiku/detail', params: [{ name: 'url', required: true, placeholder: 'https://komiku.org/manga/eternally-regressing-knight/' }], sample: { url: 'https://komiku.org/manga/eternally-regressing-knight/' } },
  { server: 'nexray', category: 'Anime', name: 'Komiku Popular', desc: 'Daftar manga populer di Komiku.', path: '/api/anime/komiku/popular', upstream: '/anime/komiku/popular', params: [{ name: 'page', required: false, placeholder: '1' }] },
  { server: 'nexray', category: 'Anime', name: 'Komiku Search', desc: 'Cari manga di Komiku.', path: '/api/anime/komiku/search', upstream: '/anime/komiku/search', params: [{ name: 'q', required: true, placeholder: 'Solo Leveling' }], sample: { q: 'Solo Leveling' } },
  { server: 'nexray', category: 'Anime', name: 'Samehadaku Schedule', desc: 'Jadwal rilis anime mingguan dari Samehadaku.', path: '/api/anime/samehadaku/schedule', upstream: '/anime/samehadaku/schedule', params: [] },

  // ---------------------------------------------------------------- Canvas
  { server: 'nexray', category: 'Canvas', name: 'Gura', desc: 'Tempel foto kamu ke template Gura.', path: '/api/canvas/gura', upstream: '/canvas/gura', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Canvas', name: 'iPhone Quote Chat v2', desc: 'Gambar quote chat iPhone.', path: '/api/canvas/iqc-v2', upstream: '/maker/iqc', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Canvas', name: 'Tribun JMK48 Twibbon', desc: 'Twibbon JMK48 dengan bingkai bulat dari foto kamu.', path: '/api/canvas/jmk', upstream: '/canvas/jmk', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Canvas', name: 'Music Card', desc: 'Kartu musik: judul lagu, nama penyanyi, dan foto.', path: '/api/canvas/musiccard', upstream: '/canvas/musiccard', fileUrl: { param: 'image_url', accept: 'image/*', required: true }, params: [{ name: 'judul', required: true, placeholder: 'Shape of You' }, { name: 'nama', required: true, placeholder: 'Ed Sheeran' }, { name: 'image_url', required: true, placeholder: 'URL gambar' }], sample: { judul: 'Shape of You', nama: 'Ed Sheeran', image_url: IMG } },
  { server: 'nexray', category: 'Canvas', name: 'Pixel Art v2', desc: 'Ubah gambar jadi pixel art.', path: '/api/canvas/pixel-art-v2', upstream: '/ephoto/pixel', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Canvas', name: 'Quotly', desc: 'Gambar quote chat ala Telegram dengan latar transparan.', path: '/api/canvas/quotly', upstream: '/canvas/quotly', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'name', required: true, placeholder: 'yannz' }, { name: 'avatar', required: true, placeholder: 'URL gambar' }, { name: 'color', required: true, placeholder: 'Putih' }], sample: { text: 'Halo apa kabar', name: 'NexRay', avatar: IMG, color: 'Putih' } },
  { server: 'nexray', category: 'Canvas', name: 'Rank Card', desc: 'Kartu rank: username, avatar, level, XP, dan status.', path: '/api/canvas/rankcard', upstream: '/canvas/rankcard', params: [{ name: 'username', required: true, placeholder: 'yannz' }, { name: 'avatar', required: true, placeholder: 'URL gambar' }, { name: 'currentxp', required: true, placeholder: '12' }, { name: 'requiredxp', required: true, placeholder: '20' }, { name: 'status', required: true, options: ['online', 'idle', 'dnd', 'offline', 'streaming'] }, { name: 'level', required: true, placeholder: '5' }, { name: 'rank', required: true, placeholder: '10' }, { name: 'progressbarcolor', required: true, placeholder: '#FFFFFF' }], sample: { username: 'ElrayyXml', avatar: IMG, currentxp: '12', requiredxp: '20', status: 'online', level: '5', rank: '10', progressbarcolor: '#FFFFFF' } },
  { server: 'nexray', category: 'Canvas', name: 'Welcome-Leave', desc: 'Gambar welcome/leave grup: judul, deskripsi, avatar, latar.', path: '/api/canvas/welcomeleave', upstream: '/canvas/v1/welcomeleave', params: [{ name: 'title', required: true, placeholder: 'Welcome...' }, { name: 'description', required: true, placeholder: '© yannz...' }, { name: 'avatar', required: true, placeholder: 'URL gambar' }, { name: 'background', required: true, placeholder: 'URL gambar' }, { name: 'color', required: true, placeholder: '#FFFFFF' }, { name: 'cardstroke', required: true, placeholder: '#000000' }], sample: { title: 'Welcome', description: '© nexray', avatar: IMG, background: IMG, color: '#FFFFFF', cardstroke: '#000000' } },
  { server: 'nexray', category: 'Canvas', name: 'YouTube-Thumbnail', desc: 'Thumbnail gaya YouTube Music: cover, judul, dan penyanyi.', path: '/api/canvas/youtube', upstream: '/canvas/youtube', params: [{ name: 'title', required: true, placeholder: 'Solana' }, { name: 'artist', required: true, placeholder: 'Alex Le Mirage' }, { name: 'coverurl', required: true, placeholder: 'https://i.scdn.co/image/xxx' }], sample: { title: 'Solana', artist: 'Alex Le Mirage', coverurl: IMG } },

  // ---------------------------------------------------------------- Downloader
  { server: 'nexray', category: 'Downloader', name: 'AIO Downloader v2', desc: 'Download videos and music from TikTok, YouTube, Facebook, Instagram and more in one endpoint.', path: '/api/download/aio-v2', upstream: '/downloader/aio', params: [{ name: 'url', required: true, placeholder: 'https://www.instagram.com/p/xxx/' }], sample: { url: 'https://www.instagram.com/reel/C1Ck8sENM94/' } },
  { server: 'nexray', category: 'Downloader', name: 'CapCut Template Downloader v2', desc: 'Download the video and metadata of a CapCut template.', path: '/api/download/capcut-v2', upstream: '/downloader/v1/capcut', params: [{ name: 'url', required: true, placeholder: 'https://www.capcut.com/t/xxx' }], sample: { url: 'https://www.capcut.com/template-detail/7299286607478181121' } },
  { server: 'nexray', category: 'Downloader', name: 'Facebook Downloader v2', desc: 'Download HD/SD videos or image posts from Facebook.', path: '/api/download/facebook-v2', upstream: '/downloader/facebook', params: [{ name: 'url', required: true, placeholder: 'https://www.facebook.com/watch/?v=xxx' }], sample: { url: 'https://www.facebook.com/watch/?v=1393572814172251' } },
  { server: 'nexray', category: 'Downloader', name: 'Google Drive Downloader v2', desc: 'Info & direct link file publik Google Drive.', path: '/api/download/gdrive-v2', upstream: '/downloader/googledrive', params: [{ name: 'url', required: true, placeholder: 'https://drive.google.com/file/d/xxx/view?usp=drivesdk' }], sample: { url: 'https://drive.google.com/file/d/1thDYWcS5p5FFhzTpTev7RUv0VFnNQyZ4/view' } },
  { server: 'nexray', category: 'Downloader', name: 'GitHub Downloader v2', desc: 'Download repo GitHub jadi ZIP, atau file-nya langsung.', path: '/api/download/github-v2', upstream: '/downloader/github', params: [{ name: 'url', required: true, placeholder: 'https://github.com/user/repo' }], sample: { url: 'https://github.com/expressjs/cors' } },
  { server: 'nexray', category: 'Downloader', name: 'Mediafire Downloader v2', desc: 'Get the file details and direct download link of a Mediafire file.', path: '/api/download/mediafire-v2', upstream: '/downloader/mediafire', params: [{ name: 'url', required: true, placeholder: 'https://www.mediafire.com/file/xxx/file.zip' }], sample: { url: 'https://www.mediafire.com/file/941xczxhn27qbby/GBWA_V12.25FF-By.SamMods-.apk/file' } },
  { server: 'nexray', category: 'Downloader', name: 'Pinterest Downloader v2', desc: 'Download original-quality images and videos from Pinterest.', path: '/api/download/pinterest-v2', upstream: '/downloader/pinterest', params: [{ name: 'url', required: true, placeholder: 'https://id.pinterest.com/pin/xxx/' }], sample: { url: 'https://pin.it/4CVodSq' } },
  { server: 'nexray', category: 'Downloader', name: 'Play (Song Search & MP3) v2', desc: 'Search a song by title or keywords and download it as MP3 320 kbps with lyrics.', path: '/api/download/play-v2', upstream: '/downloader/spotifyplay', rename: { query: 'q' }, params: [{ name: 'query', required: true, placeholder: 'GIRL YOU LOUD...' }], sample: { query: 'GIRL YOU LOUD' } },
  { server: 'nexray', category: 'Downloader', name: 'Play (Song Search & MP3) v3', desc: 'Search a song by title or keywords and download it as MP3 320 kbps with lyrics.', path: '/api/download/play-v3', upstream: '/downloader/ytplay', rename: { query: 'q' }, params: [{ name: 'query', required: true, placeholder: 'Montagem Noche...' }], sample: { query: 'Montagem Noche' } },
  { server: 'nexray', category: 'Downloader', name: 'Spotify Downloader v2', desc: 'Download a Spotify track as MP3 320 kbps with lyrics (track links only, not albums or playlists).', path: '/api/download/spotify-v2', upstream: '/downloader/spotify', params: [{ name: 'url', required: true, placeholder: 'https://open.spotify.com/track/xxx' }], sample: { url: 'https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT' } },
  { server: 'nexray', category: 'Downloader', name: 'Telegram Sticker Downloader v2', desc: 'Get the details and stickers of a Telegram sticker pack.', path: '/api/download/telestick-v2', upstream: '/tools/telegram-sticker', params: [{ name: 'url', required: true, placeholder: 'https://t.me/addstickers/xxx' }], sample: { url: 'https://t.me/addstickers/Animals' } },
  { server: 'nexray', category: 'Downloader', name: 'Tiktok Downloader v3', desc: 'Download video atau slideshow Tiktok tanpa watermark.', path: '/api/download/tiktok-v3', upstream: '/downloader/tiktok', params: [{ name: 'url', required: true, placeholder: 'https://vt.tiktok.com/xxx/' }], sample: { url: 'https://www.tiktok.com/@tiktok/video/7106594312292453675' } },
  { server: 'nexray', category: 'Downloader', name: 'X (Twitter) Downloader v2', desc: 'Download videos and images with metadata from X/Twitter posts.', path: '/api/download/twitter-v2', upstream: '/downloader/twitter', params: [{ name: 'url', required: true, placeholder: 'https://x.com/xxx/status/xxx' }], sample: { url: 'https://x.com/elonmusk/status/1349129669258448897' } },
  { server: 'nexray', category: 'Downloader', name: 'YouTube Downloader v2', desc: 'Unduh video YouTube.', path: '/api/download/youtube-v2', upstream: '/downloader/savetube', params: [{ name: 'url', required: true, placeholder: 'https://www.youtube.com/xxx' }, { name: 'quality', required: false, options: ['mp3', '144', '240', '360', '480', '720', '1080'] }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },

  // ---------------------------------------------------------------- Ephoto
  { server: 'nexray', category: 'Ephoto', name: 'Brave Green', desc: 'Filter duotone hijau-pink buat foto.', path: '/api/ephoto/bravegreen', upstream: '/ephoto/bravegreen', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },

  // ---------------------------------------------------------------- Fun
  { server: 'nexray', category: 'Fun', name: 'Teks Alay v2', desc: 'Ubah teks jadi gaya alay.', path: '/api/fun/alay-v2', upstream: '/fun/alay', params: [{ name: 'text', required: true, placeholder: 'HelloWorld' }], sample: { text: 'HelloWorld' } },
  { server: 'nexray', category: 'Fun', name: 'Live Fun Facts', desc: 'Fakta seru soal tubuhmu sejak lahir berdasarkan tanggal lahir.', path: '/api/fun/livefunfact', upstream: '/fun/livefunfact', params: [{ name: 'birthdate', required: true, placeholder: '1990-05-15' }], sample: { birthdate: '1990-05-15' } },

  // ---------------------------------------------------------------- Games
  { server: 'nexray', category: 'Games', name: 'Asah Otak v2', desc: 'Asah Otak kuis acak.', path: '/api/games/asahotak-v2', upstream: '/games/asahotak', params: [] },
  { server: 'nexray', category: 'Games', name: 'Islamic', desc: 'Kuis seputar Islam acak.', path: '/api/games/islamic', upstream: '/games/islamic', params: [] },
  { server: 'nexray', category: 'Games', name: 'Siapa Dia v2', desc: 'Kuis siapa-dia.', path: '/api/games/siapa-dia-v2', upstream: '/games/siapakahaku', params: [] },
  { server: 'nexray', category: 'Games', name: 'Susun Kata v2', desc: 'Game susun kata.', path: '/api/games/susunkata-v2', upstream: '/games/susunkata', params: [] },
  { server: 'nexray', category: 'Games', name: 'Tebak Kimia v2', desc: 'Kuis tebak-kimia.', path: '/api/games/tebak-kimia-v2', upstream: '/games/tebakkimia', params: [] },
  { server: 'nexray', category: 'Games', name: 'Tebak Lirik v2', desc: 'Kuis tebak-lirik.', path: '/api/games/tebak-lirik-v2', upstream: '/games/tebaklirik', params: [] },
  { server: 'nexray', category: 'Games', name: 'Tebak Tebak An v2', desc: 'Kuis tebak-tebakan.', path: '/api/games/tebak-tebakan-v2', upstream: '/games/tebaktebakan', params: [] },
  { server: 'nexray', category: 'Games', name: 'Teka-Teki v2', desc: 'Teka-teki acak plus jawabannya.', path: '/api/games/tekateki-v2', upstream: '/games/tekateki', params: [] },

  // ---------------------------------------------------------------- Image
  { server: 'nexray', category: 'Image', name: 'Image to ASCII v2', desc: 'Ubah gambar jadi ASCII art.', path: '/api/tools/image-ascii-v2', upstream: '/ephoto/asci', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },

  // ---------------------------------------------------------------- Info
  { server: 'nexray', category: 'Info', name: 'Info Gempa v2', desc: 'Info gempa terbaru dari BMKG.', path: '/api/info/gempa-v2', upstream: '/information/gempa', params: [] },
  { server: 'nexray', category: 'Info', name: 'Stok Grow a Garden v2', desc: 'Cek stok terbaru game Grow a Garden (Roblox).', path: '/api/info/grow-a-garden-v2', upstream: '/information/growagarden', params: [] },
  { server: 'nexray', category: 'Info', name: 'Hari Libur v2', desc: 'Jadwal hari libur nasional.', path: '/api/info/hari-libur-v2', upstream: '/information/hari-libur', params: [] },
  { server: 'nexray', category: 'Info', name: 'Jadwal Sholat v2', desc: 'Jadwal sholat harian & bulanan seluruh Indonesia.', path: '/api/info/jadwal-sholat-v2', upstream: '/information/jadwalsholat', params: [{ name: 'kota', required: true, placeholder: 'jakarta' }], sample: { kota: 'jakarta' } },
  { server: 'nexray', category: 'Info', name: 'Jadwal-Sepakbola', desc: 'Jadwal pertandingan sepak bola terbaru.', path: '/api/info/jadwalbola', upstream: '/information/jadwalbola', params: [] },
  { server: 'nexray', category: 'Info', name: 'Jadwal TV v2', desc: 'Jadwal TV hari ini.', path: '/api/info/jadwaltv-v2', upstream: '/information/jadwaltv', params: [{ name: 'channel', required: true, placeholder: 'rcti' }], sample: { channel: 'rcti' } },

  // ---------------------------------------------------------------- Maker
  { server: 'nexray', category: 'Maker', name: 'ATTP v2', desc: 'Teks animasi warna-warni (GIF), cocok buat stiker.', path: '/api/maker/attp-v2', upstream: '/maker/attp', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Balogo', desc: 'Logo teks gaya Blue Archive.', path: '/api/maker/balogo', upstream: '/maker/balogo', params: [{ name: 'text', required: true, placeholder: 'BlueArchive' }], sample: { text: 'BlueArchive' } },
  { server: 'nexray', category: 'Maker', name: 'Brat v2', desc: 'Generate viral Brat album aesthetic meme text images.', path: '/api/maker/brat-v2', upstream: '/maker/brat', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Brat Anime', desc: 'Gambar teks brat versi anime.', path: '/api/maker/bratanime', upstream: '/maker/bratanime', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Brat HD', desc: 'Gambar teks brat resolusi tinggi.', path: '/api/maker/brathd', upstream: '/maker/brathd', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Brat Video v2', desc: 'Generate an animated Brat word-by-word video in MP4 or GIF format.', path: '/api/maker/bratvid-v2', upstream: '/maker/bratvid', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Bratvid HD', desc: 'Video teks brat resolusi tinggi.', path: '/api/maker/bratvidhd', upstream: '/maker/bratvidhd', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Carbon (Code to Image) v2', desc: 'Ubah kode jadi gambar PNG tema gelap.', path: '/api/maker/carbon-v2', upstream: '/maker/codesnap', params: [{ name: 'code', required: true, placeholder: 'console.log(\'Hello World\');' }], sample: { code: 'console.log(\'Hello World\');' } },
  { server: 'nexray', category: 'Maker', name: 'Emoji to GIF v2', desc: 'Convert a standard emoji into an animated Google Noto GIF / WebP sticker.', path: '/api/maker/emojitogif-v2', upstream: '/tools/emojigif', params: [{ name: 'emoji', required: true, placeholder: '😂' }], sample: { emoji: '😂' } },
  { server: 'nexray', category: 'Maker', name: 'Message', desc: 'Gambar kotak pesan ala Windows.', path: '/api/maker/msg', upstream: '/maker/msg', params: [{ name: 'message', required: true, placeholder: 'This is a test message' }, { name: 'title', required: false, placeholder: 'Title' }, { name: 'icon', required: false, options: ['warning', 'error', 'information', 'question'] }], sample: { message: 'This is a test message' } },
  { server: 'nexray', category: 'Maker', name: 'Nulis', desc: 'Teks jadi gambar tulisan tangan di buku tulis.', path: '/api/maker/nulis', upstream: '/maker/nulis', params: [{ name: 'text', required: true, placeholder: 'Halo, ini contoh tulisan' }], sample: { text: 'Halo, ini contoh tulisan' } },
  { server: 'nexray', category: 'Maker', name: 'Qc', desc: 'Gambar quote chat: teks, nama, avatar, warna.', path: '/api/maker/qc', upstream: '/maker/qc', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'name', required: true, placeholder: 'yannz' }, { name: 'avatar', required: true, placeholder: 'URL gambar' }, { name: 'color', required: true, placeholder: 'Putih' }], sample: { text: 'Halo apa kabar', name: 'NexRay', avatar: IMG, color: 'Putih' } },
  { server: 'nexray', category: 'Maker', name: 'Remini v2', desc: 'Perjelas / HD-kan foto (unggah atau URL).', path: '/api/maker/remini-v2', upstream: '/tools/remini', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Maker', name: 'Smeme', desc: 'Bikin meme dengan teks atas dan bawah.', path: '/api/maker/smeme', upstream: '/maker/smeme', params: [{ name: 'text_atas', required: true, placeholder: 'Halo...' }, { name: 'text_bawah', required: true, placeholder: 'apa kabar...' }, { name: 'background', required: true, placeholder: 'URL gambar' }], sample: { text_atas: 'Halo', text_bawah: 'apa kabar', background: IMG } },
  { server: 'nexray', category: 'Maker', name: 'TTP v2', desc: 'Teks jadi gambar (PNG), cocok buat stiker.', path: '/api/maker/ttp-v2', upstream: '/maker/ttp', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Maker', name: 'Wasted', desc: 'Efek "WASTED" ala GTA di foto kamu.', path: '/api/maker/wasted', upstream: '/editor/wasted', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },

  // ---------------------------------------------------------------- News
  { server: 'nexray', category: 'News', name: 'Antara News v2', desc: 'Berita dari antaranews.com.', path: '/api/news/antara-v2', upstream: '/berita/antara', params: [] },
  { server: 'nexray', category: 'News', name: 'CNBC Indonesia v2', desc: 'Berita terbaru dari CNBC Indonesia.', path: '/api/news/cnbc-v2', upstream: '/berita/cnbcindonesia', params: [] },
  { server: 'nexray', category: 'News', name: 'CNN Indonesia v2', desc: 'Berita dari CNN Indonesia.', path: '/api/news/cnn-v2', upstream: '/berita/cnn', params: [] },
  { server: 'nexray', category: 'News', name: 'Free Fire News', desc: 'Berita terbaru seputar Free Fire.', path: '/api/news/ffnews', upstream: '/berita/ffnews', params: [] },
  { server: 'nexray', category: 'News', name: 'Kompas v2', desc: 'Berita dari kompas.com.', path: '/api/news/kompas-v2', upstream: '/berita/kompas', params: [] },
  { server: 'nexray', category: 'News', name: 'MLBB News', desc: 'Berita terbaru seputar Mobile Legends.', path: '/api/news/mlbb', upstream: '/berita/mlbb', params: [] },
  { server: 'nexray', category: 'News', name: 'Sindonews v2', desc: 'Berita dari sindonews.com.', path: '/api/news/sindonews-v2', upstream: '/berita/sindonews', params: [] },

  // ---------------------------------------------------------------- Primbon
  { server: 'nexray', category: 'Primbon', name: 'Arti Nama v2', desc: 'Cari arti nama berdasarkan numerologi Jawa.', path: '/api/primbon/artinama-v2', upstream: '/primbon/artinama', rename: { nama: 'name' }, params: [{ name: 'nama', required: true, placeholder: 'yannz' }], sample: { nama: 'elrayyxml' } },
  { server: 'nexray', category: 'Primbon', name: 'Kecocokan Pasangan v2', desc: 'Cek kecocokan pasangan berdasarkan nama (Neptuni Jawa).', path: '/api/primbon/cocokpasangan-v2', upstream: '/primbon/pasangan', params: [{ name: 'nama1', required: true, placeholder: 'yannz' }, { name: 'nama2', required: true, placeholder: 'fiona' }], sample: { nama1: 'elrayy', nama2: 'fiona' } },
  { server: 'nexray', category: 'Primbon', name: 'Nomor Hoki v2', desc: 'Cek nomor HP kamu hoki atau nggak.', path: '/api/primbon/nomorhoki-v2', upstream: '/primbon/nomerhoki', rename: { nomor: 'phone_number' }, params: [{ name: 'nomor', required: true, placeholder: '6285658939117' }], sample: { nomor: '6285658939117' } },
  { server: 'nexray', category: 'Primbon', name: 'Potensi Penyakit v2', desc: 'Cek potensi penyakit dari tanggal lahir.', path: '/api/primbon/penyakit-v2', upstream: '/primbon/penyakit', params: [{ name: 'tanggal', required: true, placeholder: '12' }, { name: 'bulan', required: true, placeholder: '5' }, { name: 'tahun', required: true, placeholder: '1998' }], sample: { tanggal: '12', bulan: '5', tahun: '1998' } },
  { server: 'nexray', category: 'Primbon', name: 'Ramalan Jodoh Bali v2', desc: 'Ramalan kecocokan jodoh metode Bali.', path: '/api/primbon/ramalan-jodoh-bali-v2', upstream: '/primbon/ramalanjodohbali', params: [{ name: 'nama1', required: true, placeholder: 'yannz' }, { name: 'tanggal1', required: true, placeholder: '16' }, { name: 'bulan1', required: true, placeholder: '11' }, { name: 'tahun1', required: true, placeholder: '2007' }, { name: 'nama2', required: true, placeholder: 'fiona' }, { name: 'tanggal2', required: true, placeholder: '1' }, { name: 'bulan2', required: true, placeholder: '1' }, { name: 'tahun2', required: true, placeholder: '2008' }], sample: { nama1: 'elrayy', tanggal1: '16', bulan1: '11', tahun1: '2007', nama2: 'fiona', tanggal2: '1', bulan2: '1', tahun2: '2008' } },
  { server: 'nexray', category: 'Primbon', name: 'Ramal Jodoh v2', desc: 'Ramal jodoh berdasarkan nama (Neptuni Jawa).', path: '/api/primbon/ramaljodoh-v2', upstream: '/primbon/ramalanjodoh', params: [{ name: 'nama1', required: true, placeholder: 'yannz' }, { name: 'tanggal1', required: true, placeholder: '16' }, { name: 'bulan1', required: true, placeholder: '11' }, { name: 'tahun1', required: true, placeholder: '2007' }, { name: 'nama2', required: true, placeholder: 'fiona' }, { name: 'tanggal2', required: true, placeholder: '1' }, { name: 'bulan2', required: true, placeholder: '1' }, { name: 'tahun2', required: true, placeholder: '2008' }], sample: { nama1: 'elrayy', tanggal1: '16', bulan1: '11', tahun1: '2007', nama2: 'fiona', tanggal2: '1', bulan2: '1', tahun2: '2008' } },
  { server: 'nexray', category: 'Primbon', name: 'Rezeki & Hoki v2', desc: 'Cek rejeki dan hoki berdasarkan weton lahir.', path: '/api/primbon/rezeki-hoki-v2', upstream: '/primbon/rejekihoki-weton', params: [{ name: 'tanggal', required: true, placeholder: '1' }, { name: 'bulan', required: true, placeholder: '1' }, { name: 'tahun', required: true, placeholder: '2025' }], sample: { tanggal: '1', bulan: '1', tahun: '2025' } },
  { server: 'nexray', category: 'Primbon', name: 'Sifat Usaha v2', desc: 'Cek sifat usaha/bisnis berdasarkan tanggal lahir.', path: '/api/primbon/sifat-usaha-v2', upstream: '/primbon/sifatusaha-bisnis', params: [{ name: 'tanggal', required: true, placeholder: '1' }, { name: 'bulan', required: true, placeholder: '1' }, { name: 'tahun', required: true, placeholder: '2000' }], sample: { tanggal: '1', bulan: '1', tahun: '2000' } },
  { server: 'nexray', category: 'Primbon', name: 'Zodiak v2', desc: 'Cek zodiak dari tanggal lahir.', path: '/api/primbon/zodiac-v2', upstream: '/primbon/zodiak', params: [{ name: 'zodiak', required: true, options: ['aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo', 'libra', 'scorpio', 'sagitarius', 'capricorn', 'aquarius', 'pisces'] }], sample: { zodiak: 'aries' } },

  // ---------------------------------------------------------------- Random
  { server: 'nexray', category: 'Random', name: 'Anime', desc: 'Gambar anime acak sesuai kategori (waifu, neko, hug, dan lainnya).', path: '/api/random/anime', upstream: '/random/anime', params: [{ name: 'type', required: true, options: ['waifu', 'neko', 'shinobu', 'megumin', 'bully', 'cuddle', 'cry', 'hug', 'awoo', 'kiss', 'lick', 'pat', 'smug', 'bonk', 'yeet', 'blush', 'smile', 'wave', 'highfive', 'handhold', 'nom', 'bite', 'glomp', 'slap', 'kill', 'happy', 'wink', 'poke', 'dance', 'cringe'] }], sample: { type: 'waifu' } },
  { server: 'nexray', category: 'Random', name: 'Blue-Archive', desc: 'Gambar karakter Blue Archive acak.', path: '/api/random/ba', upstream: '/random/ba', params: [] },

  // ---------------------------------------------------------------- Search
  { server: 'nexray', category: 'Search', name: '8 Font', desc: 'Cari font di 8font.', path: '/api/search/8font', upstream: '/search/8font', params: [{ name: 'q', required: true, placeholder: 'cartoon' }, { name: 'page', required: false, placeholder: '1' }], sample: { q: 'cartoon' } },
  { server: 'nexray', category: 'Search', name: 'Apple Music', desc: 'Cari lagu di Apple Music.', path: '/api/search/applemusic', upstream: '/search/applemusic', params: [{ name: 'q', required: true, placeholder: 'lauv' }], sample: { q: 'lauv' } },
  { server: 'nexray', category: 'Search', name: 'Bilibili', desc: 'Cari video di Bilibili.', path: '/api/search/bilibili', upstream: '/search/bilibili', params: [{ name: 'q', required: true, placeholder: 'rekomendasi anime' }], sample: { q: 'rekomendasi anime' } },
  { server: 'nexray', category: 'Search', name: 'CapCut', desc: 'Cari template CapCut.', path: '/api/search/capcut', upstream: '/search/capcut', params: [{ name: 'q', required: true, placeholder: 'Cinematic...' }], sample: { q: 'Cinematic' } },
  { server: 'nexray', category: 'Search', name: 'Douyin', desc: 'Cari video di Douyin.', path: '/api/search/douyin', upstream: '/search/douyin', params: [{ name: 'q', required: true, placeholder: 'funny' }], sample: { q: 'funny' } },
  { server: 'nexray', category: 'Search', name: 'GitHub Repo Search v2', desc: 'Cari repository di GitHub.', path: '/api/search/github-v2', upstream: '/search/github', params: [{ name: 'q', required: true, placeholder: 'Bot WhatsApp' }], sample: { q: 'Bot WhatsApp' } },
  { server: 'nexray', category: 'Search', name: 'Groupsor', desc: 'Cari link grup WhatsApp publik.', path: '/api/search/groupsor', upstream: '/search/groupsor', params: [{ name: 'q', required: true, placeholder: 'Cari Teman...' }], sample: { q: 'Cari Teman' } },
  { server: 'nexray', category: 'Search', name: 'HappyMood', desc: 'Cari aplikasi mod di HappyMod.', path: '/api/search/happymood', upstream: '/search/happymood', params: [{ name: 'q', required: true, placeholder: 'kinemaster' }], sample: { q: 'kinemaster' } },
  { server: 'nexray', category: 'Search', name: 'iStock', desc: 'Cari foto di iStock.', path: '/api/search/istock', upstream: '/search/istock', params: [{ name: 'q', required: true, placeholder: 'mountain' }], sample: { q: 'mountain' } },
  { server: 'nexray', category: 'Search', name: 'NPM Search v2', desc: 'Cari paket di npm.', path: '/api/search/npm-v2', upstream: '/downloader/npm', params: [{ name: 'q', required: true, placeholder: 'axios' }], sample: { q: 'axios' } },
  { server: 'nexray', category: 'Search', name: 'NPM Search v3', desc: 'Cari paket di npm.', path: '/api/search/npm-v3', upstream: '/search/npmjs', params: [{ name: 'q', required: true, placeholder: 'express' }], sample: { q: 'express' } },
  { server: 'nexray', category: 'Search', name: 'NPM Search v4', desc: 'Cari paket di npm.', path: '/api/search/npm-v4', upstream: '/stalker/npmjs', rename: { q: 'name' }, params: [{ name: 'q', required: true, placeholder: 'api-yannz' }], sample: { q: 'api-nexray' } },
  { server: 'nexray', category: 'Search', name: 'Pinterest Search v2', desc: 'Cari gambar di Pinterest.', path: '/api/search/pinterest-v2', upstream: '/search/pinterest', params: [{ name: 'q', required: true, placeholder: 'Dasha taran' }], sample: { q: 'Dasha taran' } },
  { server: 'nexray', category: 'Search', name: 'Pinterest Video', desc: 'Cari video di Pinterest.', path: '/api/search/pinterestvideo', upstream: '/search/pinterestvideo', params: [{ name: 'q', required: true, placeholder: 'Dasha taran' }], sample: { q: 'Dasha taran' } },
  { server: 'nexray', category: 'Search', name: 'Resep Masakan v2', desc: 'Cari resep masakan: bahan, langkah, dan fotonya.', path: '/api/search/resep-v2', upstream: '/search/resep', params: [{ name: 'q', required: true, placeholder: 'nasi goreng' }], sample: { q: 'nasi goreng' } },
  { server: 'nexray', category: 'Search', name: 'SFile', desc: 'Cari file di SFile.', path: '/api/search/sfile', upstream: '/search/sfile', params: [{ name: 'q', required: true, placeholder: 'Pou...' }], sample: { q: 'Pou' } },
  { server: 'nexray', category: 'Search', name: 'SoundCloud Search v2', desc: 'Search lagu di SoundCloud.', path: '/api/search/soundcloud-v2', upstream: '/search/soundcloud', params: [{ name: 'q', required: true, placeholder: 'lofi beats' }], sample: { q: 'lofi beats' } },
  { server: 'nexray', category: 'Search', name: 'Spotify Lyrics v2', desc: 'Cari lirik lagu.', path: '/api/search/spotify-lirik-v2', upstream: '/search/lyrics', rename: { title: 'q' }, params: [{ name: 'title', required: true, placeholder: 'lauv never not...' }], sample: { title: 'lauv never not' } },
  { server: 'nexray', category: 'Search', name: 'Spotify Search v2', desc: 'Cari lagu di Spotify.', path: '/api/search/spotify-v2', upstream: '/search/spotify', params: [{ name: 'q', required: true, placeholder: 'Solana Alex Le Mirage' }], sample: { q: 'Solana Alex Le Mirage' } },
  { server: 'nexray', category: 'Search', name: 'Sticker.ly Search v2', desc: 'Search sticker packs on Sticker.ly by keyword.', path: '/api/search/stickerly-v2', upstream: '/search/stickerly', params: [{ name: 'q', required: true, placeholder: 'Patrick' }], sample: { q: 'Patrick' } },
  { server: 'nexray', category: 'Search', name: 'TikTok Search v2', desc: 'Cari video TikTok.', path: '/api/search/tiktok-v2', upstream: '/search/tiktok', params: [{ name: 'q', required: true, placeholder: 'Ronaldo...' }], sample: { q: 'Ronaldo' } },
  { server: 'nexray', category: 'Search', name: 'TikTok Photo', desc: 'Cari postingan foto (slide) di TikTok.', path: '/api/search/tiktokphoto', upstream: '/search/tiktokphoto', params: [{ name: 'q', required: true, placeholder: 'nature' }], sample: { q: 'nature' } },
  { server: 'nexray', category: 'Search', name: 'TikTok Trending', desc: 'Video TikTok yang lagi trending di satu negara.', path: '/api/search/tiktoktrend', upstream: '/search/tiktoktrend', params: [{ name: 'id', required: true, placeholder: 'ID' }], sample: { id: 'ID' } },
  { server: 'nexray', category: 'Search', name: 'Wallcraft', desc: 'Cari wallpaper di Wallcraft.', path: '/api/search/wallcraft', upstream: '/search/wallcraft', params: [{ name: 'q', required: true, placeholder: 'nature' }], sample: { q: 'nature' } },
  { server: 'nexray', category: 'Search', name: 'Wikipedia Search v2', desc: 'Cari artikel Wikipedia.', path: '/api/search/wikipedia-v2', upstream: '/search/wikipedia', params: [{ name: 'q', required: true, placeholder: 'javascript' }], sample: { q: 'javascript' } },
  { server: 'nexray', category: 'Search', name: 'YouTube Search v2', desc: 'Cari video YouTube.', path: '/api/search/youtube-v2', upstream: '/search/youtube', params: [{ name: 'q', required: true, placeholder: 'Solana' }], sample: { q: 'Solana' } },

  // ---------------------------------------------------------------- Stalk
  { server: 'nexray', category: 'Stalk', name: 'Genshin Stalk v2', desc: 'Stalk profil Genshin Impact (UID).', path: '/api/stalk/genshin-v2', upstream: '/stalker/genshin', rename: { uid: 'id' }, params: [{ name: 'uid', required: true, placeholder: '856012067' }], sample: { uid: '856012067' } },
  { server: 'nexray', category: 'Stalk', name: 'GitHub Stalk v2', desc: 'Info profil GitHub publik.', path: '/api/stalk/github-v2', upstream: '/stalker/github', params: [{ name: 'username', required: true, placeholder: 'yannz' }], sample: { username: 'ElrayyXml' } },
  { server: 'nexray', category: 'Stalk', name: 'Pinterest', desc: 'Info profil Pinterest.', path: '/api/stalk/pinterest', upstream: '/stalker/pinterest', params: [{ name: 'username', required: true, placeholder: 'dims' }], sample: { username: 'dims' } },
  { server: 'nexray', category: 'Stalk', name: 'Roblox Stalk v2', desc: 'Stalk profil Roblox.', path: '/api/stalk/roblox-v2', upstream: '/stalker/roblox', rename: { user: 'username' }, params: [{ name: 'user', required: true, placeholder: 'Builderman' }], sample: { user: 'Builderman' } },
  { server: 'nexray', category: 'Stalk', name: 'Threads', desc: 'Info profil Threads.', path: '/api/stalk/threads', upstream: '/stalker/threads', params: [{ name: 'username', required: true, placeholder: 'zuck' }], sample: { username: 'zuck' } },
  { server: 'nexray', category: 'Stalk', name: 'TikTok Stalk v2', desc: 'Info profil TikTok publik.', path: '/api/stalk/tiktok-v2', upstream: '/stalker/tiktok', params: [{ name: 'username', required: true, placeholder: 'yannz' }], sample: { username: 'elrayyxml' } },
  { server: 'nexray', category: 'Stalk', name: 'YouTube Stalk v2', desc: 'Info channel YouTube: subscriber, jumlah video, video terbaru.', path: '/api/stalk/youtube-v2', upstream: '/stalker/youtube', params: [{ name: 'username', required: true, placeholder: 'MrBeast' }], sample: { username: 'MrBeast' } },

  // ---------------------------------------------------------------- Textpro
  { server: 'nexray', category: 'Textpro', name: 'Avengers', desc: 'Logo teks gaya Avengers (dua teks).', path: '/api/textpro/avengers', upstream: '/textpro/avengers', params: [{ name: 'text1', required: true, placeholder: 'yannz' }, { name: 'text2', required: true, placeholder: 'yannz' }], sample: { text1: 'elrayyxml', text2: 'nexray' } },
  { server: 'nexray', category: 'Textpro', name: 'Bear', desc: 'Efek teks gaya beruang.', path: '/api/textpro/bear', upstream: '/textpro/bear', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'BlackPink', desc: 'Efek teks gaya BLACKPINK.', path: '/api/textpro/blackpink', upstream: '/textpro/blackpink', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Cartoon Graffiti', desc: 'Efek teks graffiti kartun.', path: '/api/textpro/cartoon-graffiti', upstream: '/textpro/cartoon-graffiti', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Comic', desc: 'Efek teks gaya komik.', path: '/api/textpro/comic', upstream: '/textpro/comic', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Devil Wings', desc: 'Efek teks sayap iblis.', path: '/api/textpro/devil-wings', upstream: '/textpro/devil-wings', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Dragon Ball', desc: 'Efek teks gaya Dragon Ball.', path: '/api/textpro/dragonball', upstream: '/textpro/dragonball', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Foggy Glass', desc: 'Tulisan tangan di kaca berembun, ada pilihan latar.', path: '/api/textpro/foggy-glass', upstream: '/textpro/foggy-glass', params: [{ name: 'text', required: true, placeholder: 'yannz' }, { name: 'background', required: false, options: ['bear', 'cat', 'flower', 'heart', 'sad', 'smile'] }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Glitch', desc: 'Efek teks glitch digital.', path: '/api/textpro/glitch', upstream: '/textpro/glitch', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Graffiti v1', desc: 'Efek teks graffiti dengan dua teks.', path: '/api/textpro/graffiti', upstream: '/textpro/v1/graffiti', params: [{ name: 'text1', required: true, placeholder: 'yannz' }, { name: 'text2', required: true, placeholder: 'yannz' }], sample: { text1: 'elrayyxml', text2: 'nexray' } },
  { server: 'nexray', category: 'Textpro', name: 'Graffiti v5', desc: 'Efek teks graffiti dengan satu teks.', path: '/api/textpro/graffiti-v2', upstream: '/textpro/v5/graffiti', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Marvel', desc: 'Logo teks gaya Marvel (dua teks), ada pilihan latar.', path: '/api/textpro/marvel', upstream: '/textpro/marvel', params: [{ name: 'text1', required: true, placeholder: 'MARVEL' }, { name: 'text2', required: true, placeholder: 'STUDIOS' }, { name: 'background', required: false, options: ['logo-1', 'logo-2'] }], sample: { text1: 'MARVEL', text2: 'STUDIOS' } },
  { server: 'nexray', category: 'Textpro', name: 'Mascot', desc: 'Logo maskot (dua teks) dengan 90+ pilihan gaya.', path: '/api/textpro/mascot', upstream: '/textpro/mascot', params: [{ name: 'text1', required: true, placeholder: 'Text1' }, { name: 'text2', required: true, placeholder: 'Text2' }, { name: 'style', required: false, options: ['ninja-cat', 'cobra', 'demon-cat', 'monster', 'octopus-3', 'panda', 'sabertooth-2', 'snake', 'tiger-5', 'tiger-6', 'wolf-2', 'wolf-3', 'dragon-5', 'jet', 'knight', 'skull-3', 'skull-cyborg', 'tiger-4', 'bee-3', 'dragon-4', 'fox-3', 'goat-2', 'kitsune', 'octopus-2', 'piranha', 'wolf', 'bear-2', 'cat', 'ceberus', 'crocodile', 'dinosaur', 'dragon-3', 'eagle-3', 'horse-2', 'husky', 'kraken', 'lynx', 'sabertooth', 'assassin', 'bee-2', 'cat-2', 'demon', 'fox-2', 'gorilla', 'horus', 'octopus', 'rounin', 'scorpion', 'skull-2', 'tiger-3', 'wolver', 'tiger-2', 'tiger', 'shark', 'sabertooth-3', 'rooster', 'rhino', 'puma', 'phoenix', 'panther', 'owl', 'lion', 'horse', 'hornet', 'griffin', 'goat', 'fox', 'eagle', 'dragon2', 'dragon', 'devil', 'cobra-2', 'bull', 'bear', 'monkey', 'warrior', 'skull', 'rabbit', 'pirates', 'owl-2', 'neon-wolf', 'lion-king', 'gorilla-2', 'flash-wolf', 'fire-skull', 'eagle-2', 'dog', 'mask-skull', 'team', 'pubg', 'drift', 'bee'] }], sample: { text1: 'Text1', text2: 'Text2' } },
  { server: 'nexray', category: 'Textpro', name: 'Naruto', desc: 'Efek teks gaya Naruto.', path: '/api/textpro/naruto', upstream: '/textpro/naruto', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Painting', desc: 'Efek teks lukisan (dua teks).', path: '/api/textpro/painting', upstream: '/textpro/painting', params: [{ name: 'text1', required: true, placeholder: 'yannz' }, { name: 'text2', required: true, placeholder: 'yannz' }], sample: { text1: 'elrayyxml', text2: 'nexray' } },
  { server: 'nexray', category: 'Textpro', name: 'Pavement', desc: 'Efek tulisan di aspal.', path: '/api/textpro/pavement', upstream: '/textpro/pavement', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Pixel Glitch', desc: 'Efek teks pixel glitch.', path: '/api/textpro/pixel-glitch', upstream: '/textpro/pixel-glitch', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Typography', desc: 'Efek teks tipografi.', path: '/api/textpro/typography', upstream: '/textpro/typography', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Wet Glass', desc: 'Efek tulisan di kaca basah.', path: '/api/textpro/wetglass', upstream: '/textpro/wetglass', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Wolf Galaxy', desc: 'Logo serigala galaksi (dua teks).', path: '/api/textpro/wolf-galaxy', upstream: '/textpro/wolf-galaxy', params: [{ name: 'text1', required: true, placeholder: 'yannz' }, { name: 'text2', required: true, placeholder: 'yannz' }], sample: { text1: 'nexray', text2: 'elrayyxml' } },
  { server: 'nexray', category: 'Textpro', name: 'Write Graffiti', desc: 'Efek tulisan graffiti di tembok.', path: '/api/textpro/write-graffiti', upstream: '/textpro/write-graffiti', params: [{ name: 'text', required: true, placeholder: 'yannz' }], sample: { text: 'elrayyxml' } },

  // ---------------------------------------------------------------- Tools
  { server: 'nexray', category: 'Tools', name: 'TikTok Hashtag Analyzer v2', desc: 'Analisis hashtag TikTok: top 10, yang terkait, dan yang lagi trending.', path: '/api/analyze/tiktok-hashtag-v2', upstream: '/tools/tiktokhashtags', rename: { tag: 'hashtags' }, params: [{ name: 'tag', required: true, placeholder: '#meme' }], sample: { tag: '#meme' } },
  { server: 'nexray', category: 'Tools', name: 'Alight-Motion', desc: 'Info project Alight Motion dari link-nya.', path: '/api/tools/alightmotion', upstream: '/tools/alightmotion', params: [{ name: 'url', required: true, placeholder: 'https://alight.app/u/xxx/p/xxx' }], sample: { url: 'https://alight.app/u/xxx/p/xxx' } },
  { server: 'nexray', category: 'Tools', name: 'Blur-Face', desc: 'Blur wajah di foto otomatis.', path: '/api/tools/blurface', upstream: '/tools/blurface', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Image Convert v2', desc: 'Ubah format gambar (webp/jpeg/png/tiff).', path: '/api/tools/convert-v2', upstream: '/tools/converter', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'https://files.catbox.moe/xxx.webp' }, { name: 'format', required: false, options: ['PNG', 'MP4'] }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'DeWatermark', desc: 'Hapus watermark dari gambar.', path: '/api/tools/dewatermark', upstream: '/tools/v1/dewatermark', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Enhancer', desc: 'Perjelas kualitas gambar.', path: '/api/tools/enhancer', upstream: '/tools/v1/enhancer', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Grammar Checker v2', desc: 'Cek & benerin grammar bahasa Inggris.', path: '/api/tools/grammar-checker-v2', upstream: '/ai/grammarcheck', params: [{ name: 'text', required: true, placeholder: 'The old lighthouse stood sentinel on the rugged cliff.' }], sample: { text: 'The old lighthouse stood sentinel on the rugged cliff.' } },
  { server: 'nexray', category: 'Tools', name: 'Image to Prompt v2', desc: 'Ubah gambar jadi prompt AI (Midjourney, DALL-E, Stable Diffusion, Flux).', path: '/api/tools/image-to-prompt-v2', upstream: '/ai/image2prompt', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'OCR v2', desc: 'Baca teks dari gambar (unggah atau URL).', path: '/api/tools/ocr-v2', upstream: '/tools/ocr', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Remove Background v2', desc: 'Hapus background gambar pakai AI.', path: '/api/tools/removebg-v2', upstream: '/tools/removebg', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Remove Vocal', desc: 'Pisahin vokal dari musik (audio).', path: '/api/tools/removevokal', upstream: '/tools/removevokal', params: [{ name: 'url', required: true, placeholder: 'https://files.catbox.moe/xxx.mp3' }], sample: { url: 'https://raw.githubusercontent.com/Aiinne/scrape/main/song/sound3347.mp3' } },
  { server: 'nexray', category: 'Tools', name: 'Website Screenshot v2', desc: 'Screenshot halaman web (PNG).', path: '/api/tools/screenshot-v2', upstream: '/tools/ssweb', params: [{ name: 'url', required: true, placeholder: 'https://google.com' }, { name: 'width', required: false, placeholder: '1080' }, { name: 'height', required: false, placeholder: '1920' }, { name: 'device_scale', required: false, placeholder: '2' }], sample: { url: 'https://google.com' } },
  { server: 'nexray', category: 'Tools', name: 'Subdomain Finder', desc: 'Cari subdomain publik sebuah domain.', path: '/api/tools/subdomainfinder', upstream: '/tools/subdomainfinder', params: [{ name: 'domain', required: true, placeholder: 'google.com' }], sample: { domain: 'google.com' } },
  { server: 'nexray', category: 'Tools', name: 'Text to QR v2', desc: 'Bikin QR code dari teks atau link.', path: '/api/tools/text2qr-v2', upstream: '/tools/qrcode', params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Tools', name: 'TikTok Earnings', desc: 'Perkiraan penghasilan dan statistik akun TikTok.', path: '/api/tools/tiktokearnings', upstream: '/tools/tiktokearnings', params: [{ name: 'username', required: true, placeholder: 'mrbeast' }], sample: { username: 'mrbeast' } },
  { server: 'nexray', category: 'Tools', name: 'Track IP', desc: 'Info lokasi dan jaringan sebuah IP atau domain.', path: '/api/tools/trackip', upstream: '/tools/trackip', params: [{ name: 'target', required: true, placeholder: 'google.com' }], sample: { target: 'google.com' } },
  { server: 'nexray', category: 'Tools', name: 'Translate v2', desc: 'Terjemahin teks, bahasa asalnya dideteksi otomatis.', path: '/api/tools/translate-v2', upstream: '/tools/translate', rename: { target: 'lang' }, params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'target', required: true, placeholder: 'en' }], sample: { text: 'Halo apa kabar', target: 'en' } },
  { server: 'nexray', category: 'Tools', name: 'Image Upscale v2', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/tools/upscale-v2', upstream: '/tools/v1/upscale', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Image Upscale v3', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/tools/upscale-v3', upstream: '/tools/v4/upscale', fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'resolusi', required: true, options: ['2', '4'] }], sample: { url: IMG, resolusi: '2' } },
  { server: 'nexray', category: 'Tools', name: 'Username Generator v2', desc: 'Bikin ide username/gamertag.', path: '/api/tools/username-gen-v2', upstream: '/tools/usernamegen', rename: { keyword: 'name' }, params: [{ name: 'keyword', required: true, placeholder: 'yannz' }, { name: 'mode', required: false, options: ['instans', 'ai'] }, { name: 'theme', required: false, options: ['action', 'adventure', 'fantasy', 'historical', 'horror', 'mythology', 'nature', 'sci-fi', 'strategy'] }], sample: { keyword: 'elrayyxml' } },
  { server: 'nexray', category: 'Tools', name: 'Web Phishing', desc: 'Cek apakah sebuah link termasuk situs phishing.', path: '/api/tools/webphishing', upstream: '/tools/webphishing', params: [{ name: 'url', required: true, placeholder: 'https://example.com' }], sample: { url: 'https://example.com' } },
  { server: 'nexray', category: 'Tools', name: 'Web to ZIP', desc: 'Download isi website jadi file ZIP.', path: '/api/tools/webtozip', upstream: '/tools/webtozip', params: [{ name: 'url', required: true, placeholder: 'https://example.com' }], sample: { url: 'https://example.com' } },
  { server: 'nexray', category: 'Tools', name: 'Whats-Music', desc: 'Kenali judul lagu dari link audio.', path: '/api/tools/whatsmusic', upstream: '/tools/whatsmusic', params: [{ name: 'url', required: true, placeholder: 'https://files.catbox.moe/xxx.mp3' }], sample: { url: 'https://raw.githubusercontent.com/Aiinne/scrape/main/song/sound3347.mp3' } },
  { server: 'nexray', category: 'Tools', name: 'Hitung Winrate MLBB', desc: 'Hitung berapa kali menang beruntun buat ngejar target winrate MLBB.', path: '/api/tools/winrate-mlbb', upstream: '/tools/winrate-mlbb', params: [{ name: 'total_match', required: true, placeholder: '254' }, { name: 'wr_now', required: true, placeholder: '76.4' }, { name: 'wr_target', required: true, placeholder: '80' }], sample: { total_match: '254', wr_now: '76.4', wr_target: '80' } },
  { server: 'nexray', category: 'Tools', name: 'YouTube Summarize', desc: 'Ringkas isi video YouTube.', path: '/api/tools/youtube-summarize', upstream: '/tools/v1/youtube-summarize', params: [{ name: 'url', required: true, placeholder: 'https://youtube.com/xxx' }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Tools', name: 'YouTube Summarize v2', desc: 'Ringkas isi video YouTube.', path: '/api/tools/youtube-summarize-v2', upstream: '/tools/v2/youtube-summarize', params: [{ name: 'url', required: true, placeholder: 'https://youtube.com/xxx' }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Tools', name: 'YouTube Transcribe', desc: 'Ambil transkrip/subtitle video YouTube.', path: '/api/tools/yt-transcribe', upstream: '/tools/yt-transcribe', params: [{ name: 'url', required: true, placeholder: 'https://youtu.be/xxxx' }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },

  // ---------------------------------------------------------------- Cadangan (backupOnly)
  { server: 'nexray', category: 'AI', name: 'ChatGPT (cadangan)', desc: 'Chat with OpenAI ChatGPT for free without login.', path: '/api/alt3/ai/chatgpt', upstream: '/ai/chatgpt', backupOnly: true, rename: { prompt: 'text' }, params: [{ name: 'prompt', required: true, placeholder: 'Halo apa kabar...' }], sample: { prompt: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Gemini (cadangan)', desc: 'Chat with Google Gemini AI for free without login.', path: '/api/alt3/ai/gemini', upstream: '/ai/gemini', backupOnly: true, rename: { prompt: 'text' }, params: [{ name: 'prompt', required: true, placeholder: 'Halo apa kabar...' }, { name: 'session_id', required: false, placeholder: 'eyJjb29raWUiOiJOSUQ9NTMyPWVMZmtRUWZ5VmlSU2plZG16UzVSSjlTM1ZP...' }], sample: { prompt: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'TurboSeek AI (cadangan)', desc: 'Searches for an answer using TurboSeek AI.', path: '/api/alt3/ai/turboseek', upstream: '/ai/turboseek', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'AI', name: 'Venice (cadangan)', desc: 'Chat AI Venice.', path: '/api/alt3/ai/venice', upstream: '/ai/venice', backupOnly: true, rename: { prompt: 'text' }, params: [{ name: 'prompt', required: true, placeholder: 'Halo apa kabar...' }], sample: { prompt: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Anime', name: 'Anichin Detail (cadangan)', desc: 'Ambil detail dan daftar episode anime dari Anichin.moe.', path: '/api/alt3/anime/anichin/detail', upstream: '/anime/anichin/detail', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://anichin.cafe/seri/100-000-years-of-refining-qi/' }], sample: { url: 'https://anichin.cafe/seri/100-000-years-of-refining-qi/' } },
  { server: 'nexray', category: 'Anime', name: 'Anichin Search (cadangan)', desc: 'Cari anime/donghua dari Anichin.moe.', path: '/api/alt3/anime/anichin/search', upstream: '/anime/anichin/search', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'naruto' }, { name: 'page', required: false, placeholder: '1' }], sample: { q: 'naruto' } },
  { server: 'nexray', category: 'News', name: 'JKT48 News (cadangan)', desc: 'Berita JKT48 terbaru.', path: '/api/alt3/berita/jkt48', upstream: '/berita/jkt48', backupOnly: true, params: [] },
  { server: 'nexray', category: 'News', name: 'Merdeka (cadangan)', desc: 'Berita terkini dari Merdeka.', path: '/api/alt3/berita/merdeka', upstream: '/berita/merdeka', backupOnly: true, params: [] },
  { server: 'nexray', category: 'News', name: 'Suara (cadangan)', desc: 'Berita dari suara.com.', path: '/api/alt3/berita/suara', upstream: '/berita/suara', backupOnly: true, params: [] },
  { server: 'nexray', category: 'Canvas', name: 'Welcome-Leave (cadangan)', desc: 'Gambar welcome/leave grup: judul, deskripsi, avatar, latar.', path: '/api/alt3/canvas/v2/welcomeleave', upstream: '/canvas/v2/welcomeleave', backupOnly: true, params: [{ name: 'title', required: true, placeholder: 'Welcome...' }, { name: 'description', required: true, placeholder: '© yannz...' }, { name: 'avatar', required: true, placeholder: 'URL gambar' }, { name: 'background', required: true, placeholder: 'URL gambar' }, { name: 'border', required: true, placeholder: '#2a2e35' }, { name: 'avatarborder', required: true, placeholder: '#FFFFFF' }], sample: { title: 'Welcome', description: '© nexray', avatar: IMG, background: IMG, border: '#2a2e35', avatarborder: '#FFFFFF' } },
  { server: 'nexray', category: 'Downloader', name: 'Apple Music Downloader (cadangan)', desc: 'Download Apple Music songs as MP3.', path: '/api/alt3/downloader/applemusic', upstream: '/downloader/applemusic', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://music.apple.com/id/album/xxx/' }], sample: { url: 'https://music.apple.com/id/album/xxx/' } },
  { server: 'nexray', category: 'Downloader', name: 'Bilibili Downloader (cadangan)', desc: 'Download video dari Bilibili (bilibili.tv).', path: '/api/alt3/downloader/bilibili', upstream: '/downloader/bilibili', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.bilibili.com/video/xxx' }], sample: { url: 'https://www.bilibili.tv/id/video/4791413838696448' } },
  { server: 'nexray', category: 'Downloader', name: 'CapCut Template Downloader (cadangan)', desc: 'Download the video and metadata of a CapCut template.', path: '/api/alt3/downloader/capcut', upstream: '/downloader/capcut', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.capcut.com/t/xxx' }], sample: { url: 'https://www.capcut.com/template-detail/7299286607478181121' } },
  { server: 'nexray', category: 'Downloader', name: 'Douyin Downloader (cadangan)', desc: 'Download watermark-free videos or slide images from Douyin (TikTok China).', path: '/api/alt3/downloader/douyin', upstream: '/downloader/douyin', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.douyin.com/video/xxx' }], sample: { url: 'https://www.douyin.com/video/7256984651137273146' } },
  { server: 'nexray', category: 'Downloader', name: 'Instagram Downloader (cadangan)', desc: 'Download videos and photos from Instagram Reels and posts.', path: '/api/alt3/downloader/instagram', upstream: '/downloader/instagram', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.instagram.com/p/xxx' }], sample: { url: 'https://www.instagram.com/reel/C1Ck8sENM94/' } },
  { server: 'nexray', category: 'Downloader', name: 'Likee Downloader (cadangan)', desc: 'Download watermark-free videos from Likee.', path: '/api/alt3/downloader/likee', upstream: '/downloader/likee', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://l.likee.video/v/xxx' }], sample: { url: 'https://l.likee.video/v/Ip6sCh' } },
  { server: 'nexray', category: 'Downloader', name: 'Xiaohongshu Downloader (cadangan)', desc: 'Download images and videos with metadata from Xiaohongshu (RED) posts.', path: '/api/alt3/downloader/rednote', upstream: '/downloader/rednote', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://xhslink.com/o/xxx' }], sample: { url: 'https://xhslink.com/o/xxx' } },
  { server: 'nexray', category: 'Downloader', name: 'Scribd Downloader (cadangan)', desc: 'Get the image link of every page of a Scribd document.', path: '/api/alt3/downloader/scribd', upstream: '/downloader/scribd', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.scribd.com/document/xxx/xxx' }], sample: { url: 'https://www.scribd.com/document/xxx/xxx' } },
  { server: 'nexray', category: 'Downloader', name: 'Sfile Downloader (cadangan)', desc: 'Get the direct download link of an Sfile.co file.', path: '/api/alt3/downloader/sfile', upstream: '/downloader/sfile', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://sfile.co/xxx' }], sample: { url: 'https://sfile.co/xxx' } },
  { server: 'nexray', category: 'Downloader', name: 'SnackVideo Downloader (cadangan)', desc: 'Download video SnackVideo tanpa watermark.', path: '/api/alt3/downloader/snackvideo', upstream: '/downloader/snackvideo', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://snackvideo.com/@xxx/video/xxx' }], sample: { url: 'https://s.snackvideo.com/p/j9jKr9dR' } },
  { server: 'nexray', category: 'Downloader', name: 'SoundCloud Downloader (cadangan)', desc: 'Download lagu dari SoundCloud (MP3).', path: '/api/alt3/downloader/soundcloud', upstream: '/downloader/soundcloud', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://soundcloud.com/xxx/' }], sample: { url: 'https://soundcloud.com/issabella-marchelina/sisa-rasa-mahalini-official-audio' } },
  { server: 'nexray', category: 'Downloader', name: 'Terabox Downloader (cadangan)', desc: 'Download files and videos from Terabox links.', path: '/api/alt3/downloader/terabox', upstream: '/downloader/terabox', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.terabox.com/s/xxx' }], sample: { url: 'https://x.com/elonmusk/status/1349129669258448897' } },
  { server: 'nexray', category: 'Downloader', name: 'Threads Downloader (cadangan)', desc: 'Download videos and images from Threads posts.', path: '/api/alt3/downloader/threads', upstream: '/downloader/threads', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.threads.net/@xxx/post/xxx' }], sample: { url: 'https://www.threads.net/@zuck/post/C2SeSSYv2cn' } },
  { server: 'nexray', category: 'Downloader', name: 'Douyin Downloader (cadangan)', desc: 'Download watermark-free videos or slide images from Douyin (TikTok China).', path: '/api/alt3/downloader/v1/douyin', upstream: '/downloader/v1/douyin', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.douyin.com/video/xxx' }], sample: { url: 'https://www.douyin.com/video/7256984651137273146' } },
  { server: 'nexray', category: 'Downloader', name: 'Instagram Downloader (cadangan)', desc: 'Download videos and photos from Instagram Reels and posts.', path: '/api/alt3/downloader/v1/instagram', upstream: '/downloader/v1/instagram', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.instagram.com/reel/xxx/' }], sample: { url: 'https://www.instagram.com/reel/C1Ck8sENM94/' } },
  { server: 'nexray', category: 'Downloader', name: 'Spotify Downloader (cadangan)', desc: 'Download a Spotify track as MP3 320 kbps with lyrics (track links only, not albums or playlists).', path: '/api/alt3/downloader/v1/spotify', upstream: '/downloader/v1/spotify', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://open.spotify.com/track/xxx' }], sample: { url: 'https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT' } },
  { server: 'nexray', category: 'Downloader', name: 'YouTube Audio Downloader (cadangan)', desc: 'Download YouTube audio in the format and bitrate you choose.', path: '/api/alt3/downloader/v1/ytmp3', upstream: '/downloader/v1/ytmp3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.youtube.com/watch?v=xxx' }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Downloader', name: 'YouTube Video Downloader (cadangan)', desc: 'Download a YouTube video in the resolution you choose.', path: '/api/alt3/downloader/v1/ytmp4', upstream: '/downloader/v1/ytmp4', backupOnly: true, rename: { resolution: 'resolusi' }, params: [{ name: 'url', required: true, placeholder: 'https://www.youtube.com/watch?v=xxx' }, { name: 'resolution', required: false, options: ['1080', '720', '480', '360', '240', '144'] }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Downloader', name: 'Instagram Downloader (cadangan)', desc: 'Download videos and photos from Instagram Reels and posts.', path: '/api/alt3/downloader/v2/instagram', upstream: '/downloader/v2/instagram', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.instagram.com/p/xxx/' }], sample: { url: 'https://www.instagram.com/reel/C1Ck8sENM94/' } },
  { server: 'nexray', category: 'Downloader', name: 'YouTube Audio Downloader (cadangan)', desc: 'Download YouTube audio in the format and bitrate you choose.', path: '/api/alt3/downloader/ytmp3', upstream: '/downloader/ytmp3', backupOnly: true, params: [{ name: 'url', required: true, placeholder: 'https://www.youtube.com/xxx' }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Downloader', name: 'YouTube Video Downloader (cadangan)', desc: 'Download a YouTube video in the resolution you choose.', path: '/api/alt3/downloader/ytmp4', upstream: '/downloader/ytmp4', backupOnly: true, rename: { resolution: 'resolusi' }, params: [{ name: 'url', required: true, placeholder: 'https://www.youtube.com/watch?v=xxx' }, { name: 'resolution', required: false, options: ['2160', '1440', '1080', '720', '480', '360'] }], sample: { url: 'https://youtu.be/dQw4w9WgXcQ' } },
  { server: 'nexray', category: 'Info', name: 'Cuaca BMKG (cadangan)', desc: 'Info cuaca dari BMKG.', path: '/api/alt3/information/cuaca', upstream: '/information/cuaca', backupOnly: true, rename: { area: 'kota' }, params: [{ name: 'area', required: true, placeholder: 'Senen, Central Jakarta, DKI Jakarta' }], sample: { area: 'Senen, Central Jakarta, DKI Jakarta' } },
  { server: 'nexray', category: 'Canvas', name: 'iPhone Quote Chat (cadangan)', desc: 'Gambar quote chat iPhone.', path: '/api/alt3/maker/v1/iqc', upstream: '/maker/v1/iqc', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }, { name: 'provider', required: false, placeholder: 'INDOSAT' }, { name: 'jam', required: false, placeholder: '12:00' }, { name: 'baterai', required: false, placeholder: '50' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Primbon', name: 'Tafsir Mimpi (cadangan)', desc: 'Tafsir mimpi dari primbon Jawa.', path: '/api/alt3/primbon/tafsirmimpi', upstream: '/primbon/tafsirmimpi', backupOnly: true, params: [{ name: 'mimpi', required: true, placeholder: 'bertemu' }], sample: { mimpi: 'bertemu' } },
  { server: 'nexray', category: 'Search', name: 'Image Search (cadangan)', desc: 'Cari gambar di internet (safe search nyala).', path: '/api/alt3/search/bingimage', upstream: '/search/bingimage', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'kucing' }], sample: { q: 'kucing' } },
  { server: 'nexray', category: 'Search', name: 'Web Search (Bing) (cadangan)', desc: 'Cari apa aja di web, hasilnya cepat.', path: '/api/alt3/search/brave', upstream: '/search/brave', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'apa itu nodejs' }], sample: { q: 'apa itu nodejs' } },
  { server: 'nexray', category: 'Search', name: 'Image Search (cadangan)', desc: 'Cari gambar di internet (safe search nyala).', path: '/api/alt3/search/googleimage', upstream: '/search/googleimage', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'Dasha Taran' }], sample: { q: 'Dasha Taran' } },
  { server: 'nexray', category: 'Search', name: 'GSMArena Search (cadangan)', desc: 'Cari info HP di GSMArena.', path: '/api/alt3/search/gsmarena', upstream: '/search/gsmarena', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'iphone' }], sample: { q: 'iphone' } },
  { server: 'nexray', category: 'Search', name: 'Play Store Search (cadangan)', desc: 'Cari aplikasi di Google Play Store.', path: '/api/alt3/search/playstore', upstream: '/search/playstore', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'whatsapp' }], sample: { q: 'whatsapp' } },
  { server: 'nexray', category: 'Stalk', name: 'TikTok Posts (cadangan)', desc: 'Daftar video yang diposting akun TikTok.', path: '/api/alt3/search/tiktokuser', upstream: '/search/tiktokuser', backupOnly: true, rename: { user: 'username' }, params: [{ name: 'user', required: true, placeholder: 'yannz' }], sample: { user: 'elrayyxml' } },
  { server: 'nexray', category: 'Search', name: 'Spotify Search (cadangan)', desc: 'Cari lagu di Spotify.', path: '/api/alt3/search/v1/spotify', upstream: '/search/v1/spotify', backupOnly: true, params: [{ name: 'q', required: true, placeholder: 'wasted nightcore' }], sample: { q: 'wasted nightcore' } },
  { server: 'nexray', category: 'Stalk', name: 'Free Fire Stalk (cadangan)', desc: 'Cek nickname akun Free Fire dari ID.', path: '/api/alt3/stalker/freefire', upstream: '/stalker/freefire', backupOnly: true, rename: { id: 'uid' }, params: [{ name: 'id', required: true, placeholder: '1694332345' }], sample: { id: '1694332345' } },
  { server: 'nexray', category: 'Stalk', name: 'Instagram Stalk (cadangan)', desc: 'Info profil Instagram publik.', path: '/api/alt3/stalker/instagram', upstream: '/stalker/instagram', backupOnly: true, params: [{ name: 'username', required: true, placeholder: 'yannz' }], sample: { username: 'elrayyxml' } },
  { server: 'nexray', category: 'Check', name: 'Cek Akun MLBB (cadangan)', desc: 'Cek akun Mobile Legends: nickname, status first recharge, region.', path: '/api/alt3/stalker/mlbb', upstream: '/stalker/mlbb', backupOnly: true, rename: { uid: 'id' }, params: [{ name: 'uid', required: true, placeholder: '807663005' }, { name: 'zone', required: true, placeholder: '12230' }], sample: { uid: '807663005', zone: '12230' } },
  { server: 'nexray', category: 'Stalk', name: 'X (Twitter) Stalk (cadangan)', desc: 'Info profil X (Twitter): nama, bio, followers, avatar.', path: '/api/alt3/stalker/twitter', upstream: '/stalker/twitter', backupOnly: true, params: [{ name: 'username', required: true, placeholder: 'ronaldo' }], sample: { username: 'ronaldo' } },
  { server: 'nexray', category: 'Check', name: 'Cek Akun MLBB (cadangan)', desc: 'Cek akun Mobile Legends: nickname, status first recharge, region.', path: '/api/alt3/stalker/v1/mlbb', upstream: '/stalker/v1/mlbb', backupOnly: true, rename: { uid: 'id' }, params: [{ name: 'uid', required: true, placeholder: '807663005' }, { name: 'zone', required: true, placeholder: '12230' }], sample: { uid: '807663005', zone: '12230' } },
  { server: 'nexray', category: 'Check', name: 'Cek Akun MLBB (cadangan)', desc: 'Cek akun Mobile Legends: nickname, status first recharge, region.', path: '/api/alt3/stalker/v2/mlbb', upstream: '/stalker/v2/mlbb', backupOnly: true, rename: { uid: 'id' }, params: [{ name: 'uid', required: true, placeholder: '807663005' }, { name: 'zone', required: true, placeholder: '12230' }], sample: { uid: '807663005', zone: '12230' } },
  { server: 'nexray', category: 'Tools', name: 'DeWatermark (cadangan)', desc: 'Hapus watermark dari gambar.', path: '/api/alt3/tools/dewatermark', upstream: '/tools/dewatermark', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Maker', name: 'Emoji Mix (Emoji Kitchen) (cadangan)', desc: 'Combine two emojis into a custom Google Emoji Kitchen sticker.', path: '/api/alt3/tools/emojimix', upstream: '/tools/emojimix', backupOnly: true, params: [{ name: 'emoji1', required: true, placeholder: '😊' }, { name: 'emoji2', required: true, placeholder: '😂' }], sample: { emoji1: '😊', emoji2: '😂' } },
  { server: 'nexray', category: 'Tools', name: 'Enhancer (cadangan)', desc: 'Perjelas kualitas gambar.', path: '/api/alt3/tools/enhancer', upstream: '/tools/enhancer', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'resolusi', required: true, options: ['1', '4', '8', '16'] }], sample: { url: IMG, resolusi: '1' } },
  { server: 'nexray', category: 'Tools', name: 'Text to Speech (cadangan)', desc: 'Ubah teks jadi suara.', path: '/api/alt3/tools/tts-google', upstream: '/tools/tts-google', backupOnly: true, params: [{ name: 'text', required: true, placeholder: 'Halo apa kabar...' }], sample: { text: 'Halo apa kabar' } },
  { server: 'nexray', category: 'Tools', name: 'Remove Background (cadangan)', desc: 'Hapus background gambar pakai AI.', path: '/api/alt3/tools/v1/removebg', upstream: '/tools/v1/removebg', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'DeWatermark (cadangan)', desc: 'Hapus watermark dari gambar.', path: '/api/alt3/tools/v2/dewatermark', upstream: '/tools/v2/dewatermark', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Enhancer (cadangan)', desc: 'Perjelas kualitas gambar.', path: '/api/alt3/tools/v2/enhancer', upstream: '/tools/v2/enhancer', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }, { name: 'type', required: true, options: ['fast', 'ultra', 'restore'] }], sample: { url: IMG, type: 'fast' } },
  { server: 'nexray', category: 'Tools', name: 'Remove Background (cadangan)', desc: 'Hapus background gambar pakai AI.', path: '/api/alt3/tools/v2/removebg', upstream: '/tools/v2/removebg', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Image Upscale (cadangan)', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/alt3/tools/v2/upscale', upstream: '/tools/v2/upscale', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Image Upscale (cadangan)', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/alt3/tools/v3/upscale', upstream: '/tools/v3/upscale', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
  { server: 'nexray', category: 'Tools', name: 'Image Upscale (cadangan)', desc: 'Perbesar gambar 2x atau 4x.', path: '/api/alt3/tools/v5/upscale', upstream: '/tools/v5/upscale', backupOnly: true, fileUrl: { param: 'url', accept: 'image/*', required: true }, params: [{ name: 'url', required: true, placeholder: 'URL gambar' }], sample: { url: IMG } },
];

module.exports = SPECS.map(makeEndpoint);
